import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import PreviewNav from "../PreviewNav";
import WhatsAppIconLink from "../WhatsAppIconLink";
import "../familyvisa.css";

export const metadata: Metadata = { title: { absolute: "About FamilyVisa.ae | 800 DOCS LLC SOC" }, description: "About the private Dubai documentation and PRO services company behind FamilyVisa.ae.", alternates: { canonical: "/demos/familyvisauae/about" } };
const principles=[["Eligibility first","The reference service checks the route before the customer commits."],["One online journey","Documents, filing and follow-up are coordinated remotely, with required in-person government steps arranged when needed."],["Transparent fees","Government charges and the professional service fee are presented separately."],["Official channels","Applications are prepared and submitted through the relevant GDRFA, ICP, MOFA and other official channels on the customer's behalf."]] as const;
const stats=[["20,000+","visas processed Â· reference claim*"],["4.9 â˜…","Google rating Â· reference claim*"],["500+","Google reviews Â· reference claim*"],["100%","online service positioning Â· reference claim*"]] as const;
export default function AboutPage(){const wa="https://wa.me/9718003627";return <main className="fv"><div className="fv-top"><span>FamilyVisa.ae</span><span>Operated by 800 DOCS LLC SOC</span></div><PreviewNav/>
<section className="fv-online" style={{minHeight:560}}><div><p className="eyebrow">ABOUT FAMILYVISA.AE</p><h1>Private visa-documentation support, built around an online journey.</h1><p>FamilyVisa.ae is operated by 800 DOCS LLC SOC, a private documentation and PRO services company in Deira, Dubai. It is a third-party service provider, not a UAE government authority.</p><div className="fv-online-points"><span>âœ“ Dubai DET Commercial Licence No. 1237998</span><span>âœ“ Documentation, typing and PRO support</span><span>âœ“ Family, Golden, property, identity and business routes</span></div><WhatsAppIconLink href={wa} label="Speak with the FamilyVisa.ae team on WhatsApp"/></div><Image src="/familyvisauae-team.png" alt="FamilyVisa.ae support team in Dubai" width={1536} height={1024}/></section>
<section className="fv-section"><p className="eyebrow">HOW THE SERVICE WORKS</p><h2>Clear preparation before submission.</h2><div className="service-grid">{principles.map(([title,detail],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{detail}</p></article>)}</div></section>
<section className="fv-section" style={{background:"#f7f3ef"}}><p className="eyebrow">REFERENCE-SITE CLAIMS</p><h2>The reference business presents these service signals.</h2><div className="service-grid">{stats.map(([value,label])=><article key={label}><h3>{value}</h3><p>{label}</p></article>)}</div><p><small>*Migrated from the authorised reference site and labelled as reference claims rather than independent guarantees.</small></p></section>
<section className="fv-approval"><p className="eyebrow">BUSINESS DETAILS</p><h2>800 DOCS LLC SOC Â· Port Saeed, Deira.</h2><p>Commercial Licence No. 1237998. Registered office: Office 709, Business Village B Block, Port Saeed, Dubai, UAE. Customers may also apply directly through the relevant official government portals.</p><div className="fv-cta"><Link className="secondary" href="/demos/familyvisauae/terms-and-privacy">Read terms & privacy</Link><WhatsAppIconLink href={wa} label="Ask FamilyVisa.ae a question on WhatsApp"/></div></section>
</main>}
