"use client";
import Link from "next/link"; import {useEffect,useMemo,useState} from "react"; import {products} from "../catalog";
type Line={id:number;qty:number}; const KEY="barraid-cart";
function getCart():Line[]{try{const x=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(x)?x.filter(v=>products.some(p=>p.id===v.id)&&Number.isInteger(v.qty)&&v.qty>0):[]}catch{return[]}}
export default function Shop(){const [q,setQ]=useState("");const [cat,setCat]=useState("All");const [sort,setSort]=useState("featured");const [cart,setCart]=useState<Line[]>([]);useEffect(()=>setCart(getCart()),[]);
const save=(next:Line[])=>{setCart(next);localStorage.setItem(KEY,JSON.stringify(next))};const add=(id:number)=>{const found=cart.find(x=>x.id===id);save(found?cart.map(x=>x.id===id?{...x,qty:Math.min(20,x.qty+1)}:x):[...cart,{id,qty:1}])};
const shown=useMemo(()=>{let a=products.filter(p=>(cat==="All"||p.category===cat)&&(`${p.name} ${p.description} ${p.code}`.toLowerCase().includes(q.trim().toLowerCase())));if(sort==="low")a=[...a].sort((a,b)=>a.price-b.price);if(sort==="high")a=[...a].sort((a,b)=>b.price-a.price);return a},[q,cat,sort]);const count=cart.reduce((n,x)=>n+x.qty,0);
return <main className="min-h-screen bg-[#f5f1e8] text-[#111]"><header className="sticky top-0 z-30 border-b border-black/10 bg-[#fffdf8]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link href="/demos/barraid" className="text-2xl font-black tracking-[-.07em]">BAR<span className="text-[#b51f28]">RAID</span></Link><nav className="flex gap-3 text-sm font-black"><Link href="/demos/barraid">Home</Link><Link href="/demos/barraid/cart">Cart ({count})</Link></nav></div></header>
<section className="border-b border-black/10 bg-[#fffdf8]"><div className="mx-auto grid max-w-7xl gap-6 px-5 py-10 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><div className="text-xs font-black uppercase tracking-[.22em] text-[#b51f28]">BarRaid product collection</div><h1 className="mt-3 text-5xl font-black tracking-[-.05em] sm:text-6xl">Choose the product first.</h1><p className="mt-4 max-w-2xl text-lg leading-7 text-black/60">Large, clear product photography, upfront pricing and catalogue identifiers make it easier to compare BarRaid beer towers, dispensers and statement barware.</p></div><div className="rounded-[2rem] bg-[#f5f1e8] p-4"><img src="/barraid/official-209.jpg" alt="BarRaid 3 litre tripod beer and liquor tower" className="h-80 w-full object-contain sm:h-96"/></div></div></section>
<section className="mx-auto max-w-7xl px-5 py-10"><div className="grid gap-3 md:grid-cols-[1fr_auto_auto]"><input aria-label="Search products" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products or product code" className="rounded-xl border border-black/15 bg-white p-4"/><select aria-label="Category" value={cat} onChange={e=>setCat(e.target.value)} className="rounded-xl border border-black/15 bg-white p-4 font-bold">{["All","Beer Towers","Liquor Dispensers","Novelty Glassware"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Sort" value={sort} onChange={e=>setSort(e.target.value)} className="rounded-xl border border-black/15 bg-white p-4 font-bold"><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div>
<div className="mt-8 grid gap-6 md:grid-cols-2">{shown.map(p=><article key={p.id} className="overflow-hidden rounded-[1.5rem] border border-black/10 bg-[#fffdf8] shadow-sm"><Link href={"/demos/barraid/product/"+p.slug} className="block bg-white p-5"><img src={p.image} alt={p.name} className="h-80 w-full object-contain transition duration-500 motion-safe:hover:scale-105 sm:h-[26rem]"/></Link><div className="p-6"><div className="text-[10px] font-black uppercase tracking-[.18em] text-[#b51f28]">{p.category}</div><Link href={"/demos/barraid/product/"+p.slug} className="mt-2 block text-2xl font-black">{p.name}</Link><p className="mt-2 text-sm text-black/55">{p.description}</p><div className="mt-5 flex items-end gap-2"><b className="text-xl">₹{p.price.toLocaleString("en-IN")}</b>{p.oldPrice&&<span className="text-sm text-black/35 line-through">₹{p.oldPrice.toLocaleString("en-IN")}</span>}</div><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-black/5 px-3 py-2">Code: {p.code}</span><span className="rounded-full bg-black/5 px-3 py-2">{p.availability}</span></div><Link href={"/demos/barraid/product/"+p.slug} className="mt-4 block rounded-xl border border-black/15 py-3 text-center text-sm font-black">View product details →</Link><button disabled={p.availability==="Out Of Stock"} onClick={()=>add(p.id)} className="mt-5 w-full rounded-xl bg-[#b51f28] py-3 font-black text-white disabled:bg-black/25">{p.availability==="Out Of Stock"?"Out of stock":"Add to cart"}</button></div></article>)}</div>{!shown.length&&<div className="py-16 text-center font-bold">No matching products.</div>}</section></main>}