create table if not exists public.agency_leads (
  id bigint generated by default as identity primary key,
  name text not null,
  contact text not null,
  service text not null,
  budget text,
  timeline text,
  details text not null,
  source text default 'website',
  status text not null default 'new',
  created_at timestamptz not null default now()
);

alter table public.agency_leads enable row level security;

create index if not exists agency_leads_created_at_idx
  on public.agency_leads (created_at desc);

create index if not exists agency_leads_status_idx
  on public.agency_leads (status);

-- No public INSERT/SELECT policies are needed.
-- The Next.js API route uses the server-only Supabase service-role key,
-- which bypasses RLS. Never expose SUPABASE_SERVICE_ROLE_KEY in client code.
