"use client";
import {useMemo,useState} from "react";
const members=[
{id:"SB1001",name:"Aarohi Sharma",age:28,city:"Shimla",community:"Brahmin",job:"HR Manager",edu:"MBA",img:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=700&q=80",about:"Warm, ambitious and family-oriented. Loves travel, books and mountain mornings."},
{id:"SB1002",name:"Raghav Verma",age:31,city:"Chandigarh",community:"Khatri",job:"Product Lead",edu:"B.Tech",img:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=700&q=80",about:"Product leader who values kindness, curiosity and close family relationships."},
{id:"SB1003",name:"Mehak Thakur",age:27,city:"Mandi",community:"Rajput",job:"Educator",edu:"M.Sc",img:"https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=700&q=80",about:"Teacher, trekker and lifelong learner looking for a grounded partnership."},
{id:"SB1004",name:"Aditya Sood",age:30,city:"Delhi",community:"Brahmin",job:"Consultant",edu:"CA",img:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=700&q=80",about:"Consultant with Himachal roots. Enjoys fitness, food and meaningful conversations."},
{id:"SB1005",name:"Naina Kapoor",age:29,city:"Solan",community:"Khatri",job:"Architect",edu:"M.Arch",img:"https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=700&q=80",about:"Architect balancing modern outlook with strong family values."},
{id:"SB1006",name:"Karan Rana",age:32,city:"Kangra",community:"Rajput",job:"Entrepreneur",edu:"MBA",img:"https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=700&q=80",about:"Entrepreneur, outdoors enthusiast and family-first optimist."}
];
export default function MatchExplorer(){const [city,setCity]=useState("All");const [community,setCommunity]=useState("All");const [saved,setSaved]=useState<string[]>([]);const [open,setOpen]=useState<(typeof members)[0]|null>(null);const filtered=useMemo(()=>members.filter(m=>(city==="All"||m.city===city)&&(community==="All"||m.community===community)),[city,community]);const toggle=(id:string)=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
return <section className="explorer" id="discover"><div className="exploreTop"><div><small>LIVE DISCOVERY EXPERIENCE</small><h2>Find a match that feels <i>right.</i></h2></div><div className="savedCount">♡ {saved.length} shortlisted</div></div><div className="filterBar"><label>City<select value={city} onChange={e=>setCity(e.target.value)}>{["All","Shimla","Mandi","Solan","Kangra","Chandigarh","Delhi"].map(x=><option key={x}>{x}</option>)}</select></label><label>Community<select value={community} onChange={e=>setCommunity(e.target.value)}>{["All","Brahmin","Rajput","Khatri"].map(x=><option key={x}>{x}</option>)}</select></label><button onClick={()=>{setCity("All");setCommunity("All")}}>Reset filters</button></div><div className="matchGrid">{filtered.map(m=><article className="matchCard" key={m.id}><div className="matchPhoto" style={{backgroundImage:"url("+m.img+")"}}><span>✓ Verified</span><button aria-label={saved.includes(m.id)?"Remove "+m.name+" from shortlist":"Add "+m.name+" to shortlist"} aria-pressed={saved.includes(m.id)} className={saved.includes(m.id)?"liked":""} onClick={()=>toggle(m.id)}>♥</button></div><div className="matchBody"><small>{m.id}</small><h3>{m.name}, {m.age}</h3><p>{m.city} • {m.community}</p><b>{m.edu} • {m.job}</b><div><button onClick={()=>setOpen(m)}>View profile</button><button onClick={()=>toggle(m.id)}>{saved.includes(m.id)?"Shortlisted":"Shortlist"}</button></div></div></article>)}</div>{filtered.length===0&&<div className="empty">No exact demo matches. Reset a filter to explore more profiles.</div>}
{open&&<div className="modalWrap" role="dialog" aria-modal="true"><button className="modalBackdrop" aria-label="Close" onClick={()=>setOpen(null)}/><div className="profileModal"><button className="modalClose" aria-label="Close profile" onClick={()=>setOpen(null)}>×</button><div className="modalPhoto" style={{backgroundImage:"url("+open.img+")"}}/><div className="modalCopy"><small>✓ VERIFIED • {open.id}</small><h2>{open.name}, {open.age}</h2><p>{open.city} • {open.community}</p><h4>{open.edu} • {open.job}</h4><p>{open.about}</p><div className="modalStats"><span><b>Family</b>Verified</span><span><b>Profile</b>Complete</span><span><b>Contact</b>Protected</span></div><button className="interest" onClick={()=>setOpen(null)}>Express Interest →</button></div></div></div>}</section>}