import type { Metadata } from "next";
import "./safalbandhan.css";
import MatchExplorer from "./MatchExplorer";
import Plans from "./Plans";
import MemberPreview from "./MemberPreview";
import Registration from "./Registration";
import PlatformDepth from "./PlatformDepth";
export const metadata: Metadata={title:"SafalBandhan New | Premium Matrimonial Platform",description:"Premium matrimonial platform concept by Vishwakarma Digital Labs.",robots:{index:false,follow:false}};
const profiles=[
["Aarohi Sharma","28","Shimla","MBA • HR Manager","https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=700&q=80"],
["Raghav Verma","31","Chandigarh","B.Tech • Product Lead","https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=700&q=80"],
["Mehak Thakur","27","Mandi","M.Sc • Educator","https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=700&q=80"],
["Aditya Sood","30","Delhi","CA • Consultant","https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=700&q=80"]];
export default function Page(){return <main className="sb">
<div className="notice">SafalBandhan New • Premium concept by Vishwakarma Digital Labs</div>
<header className="nav"><a className="brand" href="#top"><span>स</span> SafalBandhan <b>NEW</b></a><nav><a href="#matches">Matches</a><a href="#how">How it works</a><a href="#stories">Stories</a><a href="#safety">Safety</a></nav><div className="navActions"><a className="ghost" href="#member">Member preview</a><a className="primary" href="#register">Register Free</a></div></header>
<section className="hero" id="top"><video className="heroVideo" autoPlay muted loop playsInline preload="metadata" poster="https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1800&q=82" aria-hidden="true"><source src="/media/safalbandhan/hero-wedding.mp4" type="video/mp4"/></video><div className="heroShade"/><div className="heroContent"><div className="eyebrow">HIMACHAL&apos;S TRUSTED MATCHMAKING • REIMAGINED</div><h1>Where meaningful<br/><em>beginnings</em> happen.</h1><p>A refined matrimonial experience built around compatibility, family values, privacy and genuine connections.</p><div className="finder"><label>I&apos;m looking for<select defaultValue="Bride"><option>Bride</option><option>Groom</option></select></label><label>Age<select defaultValue="26 - 30"><option>23 - 25</option><option>26 - 30</option><option>31 - 35</option></select></label><label>Community<select defaultValue="Any community"><option>Any community</option><option>Brahmin</option><option>Rajput</option><option>Khatri</option></select></label><a className="finderCta" href="#discover">Find Matches →</a></div><div className="heroTrust"><span>✓ Verified profiles</span><span>◈ Privacy first</span><span>♡ Personal assistance</span></div></div></section>
<section className="proof"><div><strong>Verified</strong><span>Identity-first concept</span></div><div><strong>Private</strong><span>Member-controlled visibility</span></div><div><strong>Curated</strong><span>Compatibility-led discovery</span></div><div><strong>Human</strong><span>Moderation architecture</span></div></section>
<section className="concierge"><div className="conciergeIntro"><small>A MORE PERSONAL WAY TO MATCH</small><h2>Technology for discovery.<br/><i>Human care for the decision.</i></h2><p>From the first shortlist to family conversations, the experience is designed to feel considered rather than transactional.</p></div><div className="conciergeRail"><article><span>01</span><div><strong>Tell us what matters</strong><p>Values, lifestyle, family expectations and the non-negotiables that filters usually miss.</p></div></article><article><span>02</span><div><strong>Receive thoughtful introductions</strong><p>Clear compatibility context helps families understand why a profile may be worth meeting.</p></div></article><article><span>03</span><div><strong>Move forward privately</strong><p>Share photos, contact details and family information only when the moment feels right.</p></div></article></div></section>
<section className="section" id="matches"><div className="sectionHead"><div><small>CURATED FOR YOU</small><h2>Meet people worth <i>knowing.</i></h2></div><a href="#discover">Explore all profiles →</a></div><div className="profiles">{profiles.map(([n,a,c,j,img])=><article className="profile" key={n}><div className="photo" style={{backgroundImage:"url("+img+")"}}><span className="verified">✓ Verified</span><a className="heart" href="#discover" aria-label="Explore shortlist">♡</a><div className="fade"><h3>{n}, {a}</h3><p>{c}</p></div></div><div className="profileBody"><p>{j}</p><div><span>Family verified</span><a href="#discover">View Profile</a></div></div></article>)}</div></section>
<MatchExplorer/>
<section className="values"><div className="valuesPhoto"/><div className="valuesCopy"><small>MATCHMAKING WITH INTENTION</small><h2>More than profiles.<br/><i>Real compatibility.</i></h2><p>Marriage is more than a checklist. SafalBandhan New puts values, lifestyle, family expectations and long-term compatibility at the centre of discovery.</p><div className="valueGrid">{[["✦","Smart compatibility","Thoughtful matching beyond basic filters."],["⌾","Local understanding","Built around Himachal communities and families."],["◈","Privacy controls","You decide who can see and contact you."],["✓","Verified ecosystem","Moderation and reporting designed for trust."]].map(([i,t,x])=><div key={t}><b>{i}</b><strong>{t}</strong><span>{x}</span></div>)}</div></div></section>
<section className="section how" id="how"><small>SIMPLE & RESPECTFUL</small><h2>Three steps to a new <i>chapter.</i></h2><div className="steps">{[["01","Create your profile","Tell us about yourself, family, education and what matters to you."],["02","Discover meaningful matches","Use smart filters for community, profession, city and preferences."],["03","Connect with confidence","Shortlist, express interest and connect with privacy controls."]].map(([n,t,x])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{x}</p></div>)}</div></section>
<MemberPreview/>
<section className="story" id="stories"><div><small>A SAFALBANDHAN STORY</small><blockquote>“We weren&apos;t looking for hundreds of profiles. We were looking for the one conversation that felt right.”</blockquote><p>Illustrative success-story presentation for the redesigned platform.</p><a className="storyAction" href="#register">See story format →</a></div></section>
<section className="section safety" id="safety"><div><small>SAFETY BY DESIGN</small><h2>Your journey stays <i>yours.</i></h2><p>Granular photo privacy, contact controls, profile verification, block/report tools and human moderation can make every interaction safer.</p></div><div className="safetyCards">{[["◈","Private photos","Control who can view protected photos."],["✓","Verification","Clear trust indicators for verified information."],["!","Report & block","Fast controls for unwanted interactions."]].map(([i,t,x])=><div key={t}><b>{i}</b><h3>{t}</h3><p>{x}</p></div>)}</div></section>
<Registration/>
<PlatformDepth/>
<Plans/>
<section className="cta"><small>YOUR STORY CAN START HERE</small><h2>Ready to meet someone<br/><i>meaningful?</i></h2><p>Create your profile in a few minutes. Browse with confidence and connect at your own pace.</p><a className="ctaButton" href="#register">Create Free Profile →</a><span>No payment required to register</span></section>
<footer><div className="brand"><span>स</span> SafalBandhan <b>NEW</b></div><p>Premium matrimonial platform concept • Himachal roots, modern experience.</p><div><a href="#how">About</a><a href="#trust">Privacy</a><a href="#safety">Safety</a><a href="#register">Contact</a></div><small>Portfolio concept by Vishwakarma Digital Labs. Demo profiles, names, stories, plans and operational states are illustrative.</small></footer>
</main>}