import Link from "next/link";

const serviceGroups = [
  { label: "Visas", items: [["Family residence visa", "Sponsor a spouse, child or parent with a clear document and residence route.", "family-residence-visa"], ["Family visa renewal", "Prepare a dependant renewal before expiry and understand the next steps.", "family-visa-renewal"], ["Golden Visa", "Explore long-term residence routes for qualifying applicants.", "golden-visa"], ["Property investor visa", "Understand property-led residency evidence and planning requirements.", "property-investor-visa"], ["Newborn visa", "Start the post-birth passport and residence process with a practical checklist.", "newborn-visa"]] },
  { label: "Identity & status", items: [["Emirates ID", "New ID, renewal and replacement support in one place.", "emirates-id"], ["Visa status support", "Understand your current step and the relevant official confirmation channel.", "visa-status"]] },
  { label: "Documents & business", items: [["Document attestation", "Prepare marriage, birth and other documents for UAE use.", "document-attestation"], ["Legal translation", "Prepare Arabic translations for formal UAE processes.", "legal-translation"], ["PRO services", "Government-facing support for businesses and employers.", "pro-services"]] },
] as const;

const steps = [["01", "Choose your service", "Start with the visa, ID, document or business task that matches your situation."], ["02", "Get a clear preparation list", "We identify the starting documents and the key details that affect your route."], ["03", "Understand charges before proceeding", "Official authority charges and any optional support are explained separately."], ["04", "Confirm the exact case", "Continue with the team on WhatsApp for case-specific guidance and next steps."]] as const;

export default function CustomerFirstSections() { return <>
  <section className="fv-customer-services" id="services" aria-labelledby="services-title"><div className="fv-customer-heading"><p className="eyebrow">WHAT WE HANDLE</p><h2 id="services-title">Find the service that matches your situation.</h2><p>Choose a clear starting point. Every service page explains what to prepare, what happens next and how to ask the team about your case.</p></div><div className="fv-customer-groups">{serviceGroups.map((group) => <section key={group.label} aria-label={group.label}><div className="fv-customer-group-title"><span>{group.label}</span><Link href="/demos/familyvisauae/services">See all services →</Link></div><div className="fv-customer-service-grid">{group.items.map(([title, detail, slug]) => <Link key={slug} href={slug === "visa-status" ? "/demos/familyvisauae/visa-status" : `/demos/familyvisauae/${slug}`}><h3>{title}</h3><p>{detail}</p><span>Explore service <b>→</b></span></Link>)}</div></section>)}</div></section>
  <section className="fv-customer-fees" aria-labelledby="fees-title"><div><p className="eyebrow">FEES, EXPLAINED EARLY</p><h2 id="fees-title">Know what you are paying for before you proceed.</h2><p>We do not present a vague bundle. Your route check provides a planning estimate; the team confirms the final official charges and any optional support after reviewing the case.</p><Link className="secondary" href="/demos/familyvisauae/fees">See fee transparency →</Link></div><div className="fv-customer-fee-cards"><article><span>01</span><h3>Planning estimate</h3><p>A useful starting range based on your selected route—not a final government quote.</p></article><article><span>02</span><h3>Official charges</h3><p>Fees set by the relevant authority and confirmed for the final route.</p></article><article><span>03</span><h3>Optional support</h3><p>Professional document and submission support explained separately before you commit.</p></article></div></section>
  <section className="fv-customer-process" aria-labelledby="process-title"><div className="fv-customer-heading"><p className="eyebrow">HOW IT WORKS</p><h2 id="process-title">From first question to a clear next step.</h2><p>No long forms. No unclear handoff. Start with the service, then move forward only when you understand the route.</p></div><ol>{steps.map(([number, title, detail]) => <li key={number}><b>{number}</b><div><h3>{title}</h3><p>{detail}</p></div></li>)}</ol></section>
  <section className="fv-customer-tools" aria-labelledby="tools-title"><div><p className="eyebrow">USEFUL TOOLS</p><h2 id="tools-title">Already know where you are in the process?</h2><p>Use the tool that answers your immediate question, then bring the result to the team for a case-specific review.</p></div><div><Link href="/demos/familyvisauae/checklist"><b>Preparing documents?</b><span>Build a route-based document checklist →</span></Link><Link href="/demos/familyvisauae/visa-status"><b>Already applied?</b><span>Ask for practical status support →</span></Link><Link href="/demos/familyvisauae/fees"><b>Comparing costs?</b><span>Understand fee transparency →</span></Link></div></section>
</> }
