export type DemoSite={slug:string;name:string;category:string;tagline:string;style:string;features:string[]};
export const demoSites:DemoSite[]=[
  {slug:"restaurant",name:"Saffron Table",category:"Restaurant",tagline:"Modern Indian fine dining",style:"warm editorial",features:"Menu|Reservations|Private dining".split("|")},
  {slug:"restaurant-bistro",name:"Olive & Ember",category:"Restaurant",tagline:"European bistro and wine bar",style:"earthy minimal",features:"Menu|Events|Reservations".split("|")},
  {slug:"restaurant-cafe",name:"Morning Ritual",category:"Restaurant",tagline:"Specialty coffee and all-day café",style:"bright lifestyle",features:"Menu|Locations|Order".split("|")},
  {slug:"restaurant-rooftop",name:"Skyline Social",category:"Restaurant",tagline:"Rooftop dining and nightlife",style:"dark luxury",features:"Dining|Events|Bookings".split("|")},
  {slug:"restaurant-family",name:"The Family Fork",category:"Restaurant",tagline:"Family dining made easy",style:"friendly colorful",features:"Menu|Parties|Reservations".split("|")},
  {slug:"restaurant-vegan",name:"Verdant Kitchen",category:"Restaurant",tagline:"Plant-forward kitchen",style:"organic modern",features:"Menu|Philosophy|Bookings".split("|")},
  {slug:"restaurant-bakery",name:"Maison Crumb",category:"Restaurant",tagline:"Artisan bakery and patisserie",style:"soft premium",features:"Products|Catering|Visit".split("|")},
  {slug:"restaurant-qsr",name:"Firebird Chicken",category:"Restaurant",tagline:"Fast casual ordering",style:"bold energetic",features:"Menu|Offers|Order".split("|")},
  {slug:"clinic",name:"MediNova Clinic",category:"Medical",tagline:"Multi-specialty healthcare",style:"clean clinical",features:"Specialties|Doctors|Appointments".split("|")},
  {slug:"medical-dental",name:"Pearl Dental Studio",category:"Medical",tagline:"Modern dentistry",style:"calm premium",features:"Treatments|Dentists|Booking".split("|")},
  {slug:"medical-derma",name:"Lumina Dermatology",category:"Medical",tagline:"Skin and aesthetic care",style:"soft clinical",features:"Treatments|Doctors|Consultation".split("|")},
  {slug:"medical-pediatrics",name:"LittleSteps Pediatrics",category:"Medical",tagline:"Child-first healthcare",style:"warm friendly",features:"Services|Doctors|Appointments".split("|")},
  {slug:"medical-physio",name:"MotionLab Physio",category:"Medical",tagline:"Physiotherapy and sports rehab",style:"active modern",features:"Programs|Team|Assessment".split("|")},
  {slug:"medical-eye",name:"ClearView Eye Centre",category:"Medical",tagline:"Eye care and vision correction",style:"precise modern",features:"Treatments|Surgeons|Booking".split("|")},
  {slug:"medical-wellness",name:"Harbor Mental Wellness",category:"Medical",tagline:"Mental wellness practice",style:"calm editorial",features:"Therapies|Clinicians|Consultation".split("|")},
  {slug:"medical-diagnostics",name:"Axis Diagnostics",category:"Medical",tagline:"Diagnostics and preventive testing",style:"technical clean",features:"Tests|Packages|Booking".split("|")},
  {slug:"ecommerce",name:"LumaCart",category:"E-commerce",tagline:"Modern D2C lifestyle store",style:"bold commerce",features:"Shop|Collections|Support".split("|")},
  {slug:"ecommerce-fashion",name:"Atelier North",category:"E-commerce",tagline:"Contemporary fashion label",style:"editorial fashion",features:"New in|Collections|Journal".split("|")},
  {slug:"ecommerce-beauty",name:"Aurea Beauty",category:"E-commerce",tagline:"Premium skincare",style:"soft luxury",features:"Shop|Routines|Ingredients".split("|")},
  {slug:"ecommerce-electronics",name:"VoltHaus",category:"E-commerce",tagline:"Consumer electronics store",style:"tech dark",features:"Products|Deals|Support".split("|")},
  {slug:"ecommerce-home",name:"Hearth & Form",category:"E-commerce",tagline:"Furniture and home décor",style:"architectural",features:"Rooms|Collections|Design help".split("|")},
  {slug:"ecommerce-fitness",name:"Peak Supply",category:"E-commerce",tagline:"Fitness gear and apparel",style:"sport bold",features:"Shop|Bundles|Guides".split("|")},
  {slug:"ecommerce-jewelry",name:"Solenne",category:"E-commerce",tagline:"Fine jewelry boutique",style:"luxury minimal",features:"Collections|Bespoke|Care".split("|")},
  {slug:"ecommerce-grocery",name:"FreshBasket",category:"E-commerce",tagline:"Online grocery delivery",style:"fresh utility",features:"Shop|Offers|Delivery".split("|")},
  {slug:"real-estate",name:"Aurelia Property",category:"Real Estate",tagline:"Premium property discovery",style:"luxury dark",features:"Properties|Areas|Viewings".split("|")},
  {slug:"real-estate-commercial",name:"Gridline Commercial",category:"Real Estate",tagline:"Commercial property advisory",style:"corporate modern",features:"Properties|Services|Enquiry".split("|")},
  {slug:"real-estate-luxury",name:"Maison Estates",category:"Real Estate",tagline:"Luxury homes and estates",style:"editorial luxury",features:"Homes|Destinations|Private viewings".split("|")},
  {slug:"real-estate-rentals",name:"NestLane Rentals",category:"Real Estate",tagline:"Long-term rental discovery",style:"friendly utility",features:"Rentals|Areas|Apply".split("|")},
  {slug:"real-estate-developer",name:"Crestline Developments",category:"Real Estate",tagline:"Residential developments",style:"architectural",features:"Projects|Company|Enquire".split("|")},
  {slug:"real-estate-investment",name:"YieldStone",category:"Real Estate",tagline:"Property investment advisory",style:"finance premium",features:"Opportunities|Research|Consult".split("|")},
  {slug:"real-estate-holiday",name:"Coast & Key",category:"Real Estate",tagline:"Holiday homes and villas",style:"coastal lifestyle",features:"Villas|Destinations|Book".split("|")},
  {slug:"real-estate-broker",name:"UrbanKey Realty",category:"Real Estate",tagline:"City brokerage",style:"urban modern",features:"Buy|Sell|Agents".split("|")},
  {slug:"service-business",name:"Northstar Advisory",category:"Professional Services",tagline:"Business advisory and consulting",style:"corporate premium",features:"Solutions|Industries|Consultation".split("|")},
  {slug:"services-legal",name:"Crown & Vale Legal",category:"Professional Services",tagline:"Corporate legal practice",style:"formal editorial",features:"Practices|Team|Consultation".split("|")},
  {slug:"services-accounting",name:"LedgerWorks",category:"Professional Services",tagline:"Accounting and CFO services",style:"clean corporate",features:"Services|Industries|Book call".split("|")},
  {slug:"services-marketing",name:"SignalHouse",category:"Professional Services",tagline:"Growth marketing studio",style:"creative bold",features:"Services|Work|Start project".split("|")},
  {slug:"services-architecture",name:"Formline Studio",category:"Professional Services",tagline:"Architecture and interiors",style:"visual minimal",features:"Projects|Studio|Enquire".split("|")},
  {slug:"services-logistics",name:"Atlas Freight",category:"Professional Services",tagline:"Freight and logistics services",style:"industrial modern",features:"Solutions|Network|Quote".split("|")},
  {slug:"services-education",name:"Summit Academy",category:"Professional Services",tagline:"Education and coaching",style:"academic modern",features:"Programs|Faculty|Admissions".split("|")},
  {slug:"services-travel",name:"Meridian Travel",category:"Professional Services",tagline:"Bespoke travel planning",style:"editorial travel",features:"Journeys|Destinations|Plan trip".split("|")},
];
export const demoCategories=["Restaurant","Medical","E-commerce","Real Estate","Professional Services"] as const;