export type PortfolioDemo = {
  label: string;
  icon: string;
  title: string;
  text: string;
  tags: string[];
  href: string;
  card: string;
  glow: string;
  labelClass: string;
  button: string;
};

export const portfolioDemos: PortfolioDemo[] = [
  {
    label: "LIVE RESTAURANT WEBSITE",
    icon: "🍽️",
    title: "Saffron Table",
    text: "Premium restaurant website experience with interactive menu, reservations and tasting-list flow.",
    tags: ["Live Demo", "Menu", "Reservations", "Gallery"],
    href: "https://vdl.vliab.workers.dev/demos/restaurant",
    card: "border-amber-300/20 bg-gradient-to-br from-[#5b2018] via-[#2d1512] to-[#153e34] rounded-[3.5rem_3.5rem_1rem_1rem]",
    glow: "bg-amber-300/20",
    labelClass: "text-amber-300",
    button: "border-amber-300/25 bg-amber-300/10 text-amber-200 group-hover:bg-amber-300 group-hover:text-[#2d1512]",
  },
  {
    label: "AI AGENT",
    icon: "✦",
    title: "NOVA AI Operations Copilot",
    text: "Agent workspace with live chat simulation, connected tools, RAG indicators and automation safeguards.",
    tags: ["AI Agent", "RAG", "Automation"],
    href: "/demos/ai-assistant",
    card: "border-violet-300/20 bg-gradient-to-br from-[#23135a] via-[#101744] to-[#073448] rounded-[2.6rem] ring-1 ring-cyan-300/10",
    glow: "bg-cyan-300/20",
    labelClass: "text-cyan-300",
    button: "border-cyan-300/25 bg-cyan-300/10 text-cyan-200 group-hover:bg-cyan-400 group-hover:text-slate-950",
  },
  {
    label: "LEAD GENERATION",
    icon: "↗",
    title: "Northstar Growth Platform",
    text: "Conversion-first business platform with lead flow, pipeline visuals and an interactive ROI calculator.",
    tags: ["Lead Capture", "CRM", "Analytics"],
    href: "/demos/service-business",
    card: "border-sky-300/20 bg-gradient-to-br from-[#0c3d69] via-[#0c3850] to-[#08604f] rounded-none border-2",
    glow: "bg-emerald-300/20",
    labelClass: "text-emerald-300",
    button: "border-emerald-300/25 bg-emerald-300/10 text-emerald-200 group-hover:bg-emerald-300 group-hover:text-[#083c35]",
  },
  {
    label: "HIGH-DEMAND ECOMMERCE",
    icon: "🛍️",
    title: "LumaCart D2C Store",
    text: "Production-style D2C store with search, product variants, wishlist, quantity cart, coupons, shipping logic and checkout.",
    tags: ["E-commerce", "Cart", "D2C"],
    href: "/demos/ecommerce",
    card: "border-orange-300/20 bg-gradient-to-br from-[#7c2d12] via-[#9a3412] to-[#365314] rounded-none border-4",
    glow: "bg-lime-300/20",
    labelClass: "text-lime-300",
    button: "border-lime-300/25 bg-lime-300/10 text-lime-200 group-hover:bg-lime-300 group-hover:text-black",
  },
  {
    label: "LIVE CLINIC WEBSITE",
    icon: "🏥",
    title: "MediNova Clinic Portal",
    text: "Live healthcare website demo with specialty filters, doctor booking, visit modes, patient intake, fee summary and portal preview.",
    tags: ["Live Demo", "Booking", "Healthcare", "Portal"],
    href: "https://vdl.vliab.workers.dev/demos/clinic",
    card: "border-teal-300/20 bg-gradient-to-br from-[#134e4a] via-[#155e75] to-[#164e63] rounded-[3rem]",
    glow: "bg-cyan-300/20",
    labelClass: "text-cyan-200",
    button: "border-cyan-300/25 bg-cyan-300/10 text-cyan-100 group-hover:bg-cyan-300 group-hover:text-teal-950",
  },
  {
    label: "LIVE REAL ESTATE WEBSITE",
    icon: "🏡",
    title: "Aurelia Property Portal",
    text: "Live real-estate website demo with luxury property discovery, filters, viewing requests and an interactive mortgage estimator.",
    tags: ["Live Demo", "Listings", "Search", "Mortgage"],
    href: "https://vdl.vliab.workers.dev/demos/real-estate",
    card: "border-yellow-200/20 bg-gradient-to-br from-[#3f3f46] via-[#18181b] to-[#713f12] rounded-none border-y-2",
    glow: "bg-yellow-300/20",
    labelClass: "text-yellow-200",
    button: "border-yellow-200/25 bg-yellow-200/10 text-yellow-100 group-hover:bg-yellow-200 group-hover:text-black",
  },
  {
    label: "EDTECH / COACHING",
    icon: "🎓",
    title: "SkillForge LMS",
    text: "Modern learning portal with course progress, lessons, quiz interaction and live-class touchpoints.",
    tags: ["LMS", "Courses", "Quiz"],
    href: "/demos/lms",
    card: "border-violet-300/20 bg-gradient-to-br from-[#4c1d95] via-[#312e81] to-[#9a3412] rounded-[3rem_0.75rem_3rem_0.75rem]",
    glow: "bg-yellow-300/20",
    labelClass: "text-yellow-200",
    button: "border-yellow-200/25 bg-yellow-200/10 text-yellow-100 group-hover:bg-yellow-300 group-hover:text-violet-950",
  },
  {
    label: "B2B SAAS / CRM",
    icon: "📊",
    title: "PipelineOS CRM",
    text: "Production-style CRM with lead capture, forecasting, scoring, activity history, pipeline stages and AI-assisted follow-ups.",
    tags: ["CRM", "SaaS", "Pipeline"],
    href: "/demos/crm",
    card: "border-indigo-300/20 bg-gradient-to-br from-[#312e81] via-[#1e3a8a] to-[#065f46] rounded-lg",
    glow: "bg-emerald-300/20",
    labelClass: "text-indigo-200",
    button: "border-indigo-200/25 bg-indigo-200/10 text-indigo-100 group-hover:bg-indigo-300 group-hover:text-indigo-950",
  },
  {
    label: "LOCAL SERVICES MARKETPLACE",
    icon: "🧰",
    title: "Fixly Home Services",
    text: "On-demand home-services booking with instant estimates, schedule selection and provider workflow.",
    tags: ["Marketplace", "Booking", "Pricing"],
    href: "/demos/home-services",
    card: "border-orange-300/20 bg-gradient-to-br from-[#1e3a5f] via-[#172554] to-[#9a3412] rounded-none border-4",
    glow: "bg-orange-300/20",
    labelClass: "text-orange-200",
    button: "border-orange-200/25 bg-orange-200/10 text-orange-100 group-hover:bg-orange-300 group-hover:text-slate-950",
  },
  {
    label: "LOGISTICS / OPERATIONS",
    icon: "🚚",
    title: "RoutePilot Logistics",
    text: "Shipment tracking, live route progress, fleet KPIs and operations automation dashboard.",
    tags: ["Tracking", "Fleet", "Dashboard"],
    href: "/demos/logistics",
    card: "border-cyan-300/20 bg-gradient-to-br from-[#083344] via-[#0c4a6e] to-[#064e3b] rounded-sm",
    glow: "bg-cyan-300/20",
    labelClass: "text-cyan-200",
    button: "border-cyan-200/25 bg-cyan-200/10 text-cyan-100 group-hover:bg-cyan-300 group-hover:text-slate-950",
  },
];
