"use client";
import {useMemo,useState} from "react";

type P={id:number;name:string;cat:string;price:number;old?:number;badge?:string;desc:string};
type Line={id:number;qty:number};
const ps:P[]=[
{id:1,name:"3L Draft Beer Tower",cat:"Beer Towers",price:3599,old:4199,badge:"BESTSELLER",desc:"3 litre tabletop draft tower with ice-tube style cooling chamber for parties, bars and hospitality."},
{id:2,name:"Double Gas Pump Liquor Dispenser",cat:"Liquor Dispensers",price:1999,badge:"BAR PICK",desc:"Twin-pour countertop dispenser inspired by classic fuel pumps for measured, theatrical serving."},
{id:3,name:"Green Beer Boot Glass",cat:"Novelty Glassware",price:599,desc:"Statement boot-shaped beer glass for home bars, gifting, parties and venue presentation."},
{id:4,name:"Santa Claus Round Dispenser",cat:"Liquor Dispensers",price:1599,badge:"GIFT PICK",desc:"Novelty round beverage dispenser designed for festive counters, gifting and party service."},
{id:5,name:"Amazing Cup LED Dispenser",cat:"Beer Towers",price:3599,badge:"LED",desc:"Illuminated beverage tower made to keep the serve visible across party and nightclub counters."},
{id:6,name:"Blue Beer Boot Glass",cat:"Novelty Glassware",price:599,desc:"Blue boot-shaped novelty glassware for memorable beer service, gifting and display."}
];
const cats=["All","Beer Towers","Liquor Dispensers","Novelty Glassware"];
const wa="919868107595";
function Visual({p}:{p:P}){return <div className="relative grid h-72 place-items-center overflow-hidden bg-[radial-gradient(circle_at_50%_30%,#fff_0,#f5f1e8_45%,#ded7c9_100%)]">
<div className="absolute left-4 top-4 rounded-full bg-[#111] px-3 py-1 text-[10px] font-black tracking-widest text-white">{p.badge||"BARRAID"}</div>
<div className={"relative border-2 border-[#7c8587] bg-[linear-gradient(110deg,#111,#8c9699_38%,#f2f4f2_49%,#565e61_62%,#151819)] shadow-2xl "+(p.cat==="Beer Towers"?"h-52 w-24 rounded-[42px_42px_20px_20px]":p.cat==="Novelty Glassware"?"h-44 w-28 [clip-path:polygon(18%_0,82%_0,70%_100%,30%_100%)]":"h-40 w-40 rounded-[35%]")}/>
<div className="absolute bottom-4 text-[10px] font-black uppercase tracking-[.18em] text-black/45">Product preview · replace with final packshot</div></div>}
export default function BarRaidDemoClient(){
const [cat,setCat]=useState("All"),[q,setQ]=useState(""),[sort,setSort]=useState("featured"),[cart,setCart]=useState<Line[]>([]),[drawer,setDrawer]=useState(false),[detail,setDetail]=useState<P|null>(null),[checkout,setCheckout]=useState(false),[ordered,setOrdered]=useState(false),[menu,setMenu]=useState(false);
const filtered=useMemo(()=>ps.filter(p=>(cat==="All"||p.cat===cat)&&(!q||p.name.toLowerCase().includes(q.toLowerCase())||p.cat.toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:a.id-b.id),[cat,q,sort]);
const count=cart.reduce((a,l)=>a+l.qty,0),subtotal=cart.reduce((a,l)=>a+(ps.find(p=>p.id===l.id)?.price||0)*l.qty,0),shipping=subtotal>=2999||!subtotal?0:149,total=subtotal+shipping;
const add=(p:P)=>{setCart(c=>{const x=c.find(l=>l.id===p.id);return x?c.map(l=>l.id===p.id?{...l,qty:l.qty+1}:l):[...c,{id:p.id,qty:1}]});setDrawer(true)};
const qty=(id:number,d:number)=>setCart(c=>c.flatMap(l=>l.id!==id?[l]:l.qty+d>0?[{...l,qty:l.qty+d}]:[]));
const quote=(p?:P)=>window.open("https://wa.me/"+wa+"?text="+encodeURIComponent("Hello BarRaid, I would like a bulk/trade quote"+(p?" for "+p.name:"")+". Please share MOQ, custom branding and best price."),"_blank","noopener,noreferrer");
return <main className="min-h-screen bg-[#f5f1e8] text-[#111]">
<div className="bg-[#b51f28] px-4 py-2 text-center text-[11px] font-black uppercase tracking-[.16em] text-white">Retail shopping • Bulk pricing on WhatsApp • India delivery</div>
<header className="sticky top-0 z-40 border-b border-black/15 bg-[#f5f1e8]/95 backdrop-blur">
<div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4"><a href="#top" className="text-2xl font-black tracking-[-.07em]">BAR<span className="text-[#b51f28]">RAID</span></a>
<nav className="hidden items-center gap-6 text-sm font-black md:flex"><a href="#shop">Shop</a><a href="#categories">Categories</a><a href="#bulk">Bulk orders</a><a href="#help">Delivery & returns</a></nav>
<div className="flex gap-2"><button onClick={()=>setMenu(!menu)} className="rounded-full border border-black px-4 py-2 text-sm font-black md:hidden">Menu</button><button onClick={()=>setDrawer(true)} className="rounded-full bg-[#111] px-5 py-2 text-sm font-black text-white">Cart ({count})</button></div></div>
{menu&&<div className="border-t border-black/10 px-5 py-4 md:hidden"><div className="flex flex-col gap-3 font-bold"><a href="#shop">Shop</a><a href="#categories">Categories</a><a href="#bulk">Bulk orders</a><a href="#help">Delivery & returns</a></div></div>}</header>

<section id="top" className="bg-[#101417] text-white"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-16 lg:grid-cols-2 lg:py-24">
<div><div className="inline-flex rounded-full border border-[#e8b04a]/50 bg-[#e8b04a]/10 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-[#ffd27b]">Barware that gets noticed</div><h1 className="mt-6 text-5xl font-black leading-[.94] tracking-[-.055em] sm:text-7xl">Make every pour <span className="text-[#e8b04a]">the main event.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/65">Beer towers, liquor dispensers and novelty glassware for home bars, parties, restaurants, clubs and gifting.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#shop" className="rounded-full bg-[#b51f28] px-7 py-4 font-black text-white">Shop products ↓</a><button onClick={()=>quote()} className="rounded-full border border-white/25 px-7 py-4 font-black">Get bulk quote ↗</button></div></div>
<div className="rounded-[2rem] bg-[#f5f1e8] p-4 text-black shadow-2xl"><Visual p={ps[0]}/><div className="flex items-end justify-between p-5"><div><div className="text-xs font-black uppercase tracking-widest text-[#b51f28]">Featured</div><div className="mt-1 text-2xl font-black">{ps[0].name}</div><div className="mt-1 font-black">₹{ps[0].price.toLocaleString("en-IN")}</div></div><button onClick={()=>setDetail(ps[0])} className="rounded-full bg-black px-5 py-3 text-sm font-black text-white">View product</button></div></div></div></section>

<section className="border-b border-black/15 bg-white"><div className="mx-auto grid max-w-7xl grid-cols-2 md:grid-cols-4">{["Clear retail pricing","Secure checkout ready","Bulk & custom orders","Delivery support"].map(x=><div key={x} className="border-r border-black/10 p-5 text-center text-xs font-black uppercase tracking-wider">✓ {x}</div>)}</div></section>
<section id="categories" className="mx-auto max-w-7xl px-5 py-14"><div className="text-xs font-black uppercase tracking-[.2em] text-[#b51f28]">Shop by category</div><div className="mt-5 grid gap-4 md:grid-cols-3">{cats.slice(1).map((c,i)=><button key={c} onClick={()=>{setCat(c);document.getElementById("shop")?.scrollIntoView({behavior:"smooth"})}} className={"min-h-48 p-6 text-left text-white "+(i===0?"bg-[#b51f28]":i===1?"bg-[#182126]":"bg-[#9b6b37]")}><div className="text-3xl font-black">{c}</div><div className="mt-16 text-sm font-bold">Explore collection →</div></button>)}</div></section>

<section id="shop" className="mx-auto max-w-7xl px-5 py-16"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="text-xs font-black uppercase tracking-[.2em] text-[#b51f28]">BarRaid shop</div><h2 className="mt-2 text-4xl font-black">Products you can actually see.</h2></div><div className="flex flex-wrap gap-2">{cats.map(c=><button key={c} onClick={()=>setCat(c)} className={"rounded-full px-4 py-2 text-sm font-bold "+(cat===c?"bg-black text-white":"border border-black/20 bg-white")}>{c}</button>)}</div></div>
<div className="mt-6 grid gap-3 sm:grid-cols-[1fr_auto]"><input value={q} onChange={e=>setQ(e.target.value)} className="rounded-full border border-black/20 bg-white px-5 py-3 outline-none" placeholder="Search beer tower, dispenser, glassware…"/><select value={sort} onChange={e=>setSort(e.target.value)} className="rounded-full border border-black/20 bg-white px-5 py-3 font-bold"><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div>
<div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(p=><article key={p.id} className="overflow-hidden rounded-2xl border border-black/10 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><button className="block w-full" onClick={()=>setDetail(p)}><Visual p={p}/></button><div className="p-6"><div className="text-[10px] font-black uppercase tracking-[.18em] text-[#b51f28]">{p.cat}</div><button onClick={()=>setDetail(p)} className="mt-2 text-left text-2xl font-black">{p.name}</button><p className="mt-3 min-h-12 text-sm leading-6 text-black/55">{p.desc}</p><div className="mt-5 flex items-end gap-2"><b className="text-xl">₹{p.price.toLocaleString("en-IN")}</b>{p.old&&<span className="text-sm text-black/35 line-through">₹{p.old.toLocaleString("en-IN")}</span>}</div><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={()=>add(p)} className="rounded-xl bg-[#b51f28] py-3 text-sm font-black text-white">Add to cart</button><button onClick={()=>quote(p)} className="rounded-xl border border-black/20 py-3 text-sm font-black">Bulk quote</button></div></div></article>)}</div></section>

<section id="bulk" className="bg-[#182126] text-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-16 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="text-xs font-black uppercase tracking-[.2em] text-[#ffd27b]">Hotels • clubs • restaurants • gifting</div><h2 className="mt-3 text-4xl font-black">Buying in quantity?</h2><p className="mt-4 max-w-2xl leading-7 text-white/60">Ask BarRaid for MOQ, volume pricing, logo/custom-colour possibilities and availability. Retail customers can continue through cart normally.</p></div><button onClick={()=>quote()} className="rounded-full bg-[#e8b04a] px-7 py-4 font-black text-black">WhatsApp bulk enquiry ↗</button></div></section>
<section id="help" className="mx-auto grid max-w-7xl gap-4 px-5 py-16 md:grid-cols-3">{[["Delivery","Shipping cost and estimated delivery are shown before order confirmation."],["Returns","Return eligibility should be confirmed against the final BarRaid policy before launch."],["Payments","Checkout UI is prepared for UPI, card and COD integration; live gateway credentials are required for production."]].map(([h,t])=><div key={h} className="border border-black/15 bg-white p-6"><h3 className="text-xl font-black">{h}</h3><p className="mt-3 text-sm leading-6 text-black/55">{t}</p></div>)}</section>
<footer className="border-t border-black/15 bg-white px-5 py-10 text-center text-xs font-bold text-black/45">BarRaid ecommerce preview · Built by Vishwakarma Digital Labs</footer>

{detail&&<div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/70 p-4" onClick={()=>setDetail(null)}><div onClick={e=>e.stopPropagation()} className="grid w-full max-w-4xl overflow-hidden rounded-3xl bg-[#f5f1e8] md:grid-cols-2"><Visual p={detail}/><div className="p-7"><div className="flex justify-between"><div><div className="text-xs font-black uppercase tracking-widest text-[#b51f28]">{detail.cat}</div><h3 className="mt-2 text-3xl font-black">{detail.name}</h3></div><button onClick={()=>setDetail(null)} className="text-3xl">×</button></div><p className="mt-5 leading-7 text-black/60">{detail.desc}</p><div className="mt-5 text-3xl font-black">₹{detail.price.toLocaleString("en-IN")}</div><div className="mt-7 grid gap-3"><button onClick={()=>{add(detail);setDetail(null)}} className="rounded-xl bg-[#b51f28] py-4 font-black text-white">Add to cart →</button><button onClick={()=>quote(detail)} className="rounded-xl border border-black/20 py-4 font-black">Ask bulk price on WhatsApp</button></div><div className="mt-5 grid grid-cols-3 gap-2 text-center text-[10px] font-bold"><div className="bg-white p-3">Retail order</div><div className="bg-white p-3">Bulk quote</div><div className="bg-white p-3">Support</div></div></div></div></div>}

{drawer&&<div className="fixed inset-0 z-50 bg-black/55" onClick={()=>setDrawer(false)}><aside onClick={e=>e.stopPropagation()} className="ml-auto flex h-full w-full max-w-md flex-col bg-[#f5f1e8] p-6"><div className="flex justify-between"><div><h3 className="text-2xl font-black">Your cart</h3><p className="text-xs text-black/45">{count} item{count===1?"":"s"}</p></div><button onClick={()=>setDrawer(false)} className="text-3xl">×</button></div><div className="mt-6 flex-1 space-y-3 overflow-y-auto">{!cart.length?<div className="border border-dashed border-black/20 p-8 text-center text-black/45">Your cart is empty.</div>:cart.map(l=>{const p=ps.find(x=>x.id===l.id)!;return <div key={l.id} className="bg-white p-4"><div className="flex justify-between gap-4"><b>{p.name}</b><b>₹{(p.price*l.qty).toLocaleString("en-IN")}</b></div><div className="mt-3 flex items-center gap-2"><button onClick={()=>qty(l.id,-1)} className="h-8 w-8 bg-black/5">−</button><b>{l.qty}</b><button onClick={()=>qty(l.id,1)} className="h-8 w-8 bg-black/5">+</button></div></div>})}</div>{!!cart.length&&<div className="border-t border-black/15 pt-5"><div className="flex justify-between text-sm"><span>Subtotal</span><b>₹{subtotal.toLocaleString("en-IN")}</b></div><div className="mt-2 flex justify-between text-sm"><span>Shipping</span><b>{shipping?"₹"+shipping:"FREE"}</b></div><div className="mt-3 flex justify-between text-xl font-black"><span>Total</span><span>₹{total.toLocaleString("en-IN")}</span></div><button onClick={()=>{setDrawer(false);setCheckout(true)}} className="mt-5 w-full rounded-xl bg-[#b51f28] py-4 font-black text-white">Checkout →</button></div>}</aside></div>}

{checkout&&<div className="fixed inset-0 z-[60] grid place-items-center overflow-y-auto bg-black/70 p-4"><div className="w-full max-w-2xl rounded-3xl bg-white p-7">{ordered?<div className="py-10 text-center"><div className="text-5xl">✓</div><h3 className="mt-4 text-3xl font-black">Demo order confirmed</h3><p className="mt-3 text-black/55">The storefront flow is working. Live payment and fulfilment will be connected with BarRaid credentials before production launch.</p><button onClick={()=>{setOrdered(false);setCheckout(false);setCart([])}} className="mt-6 rounded-xl bg-black px-6 py-3 font-black text-white">Done</button></div>:<><div className="flex justify-between"><div><div className="text-xs font-black uppercase tracking-widest text-[#b51f28]">Checkout</div><h3 className="mt-1 text-3xl font-black">Delivery details</h3></div><button onClick={()=>setCheckout(false)} className="text-3xl">×</button></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><input className="border p-3" placeholder="Full name"/><input className="border p-3" placeholder="Phone"/><input className="border p-3 sm:col-span-2" placeholder="Address"/><input className="border p-3" placeholder="City"/><input className="border p-3" placeholder="PIN code"/></div><div className="mt-5 grid gap-2 sm:grid-cols-3">{["UPI","Card","Cash on delivery"].map(x=><div key={x} className="border p-4 font-bold">○ {x}</div>)}</div><div className="mt-6 flex items-center justify-between bg-[#f5f1e8] p-5"><div><div className="text-xs text-black/45">PAYABLE</div><b className="text-2xl">₹{total.toLocaleString("en-IN")}</b></div><button onClick={()=>setOrdered(true)} className="rounded-xl bg-[#b51f28] px-6 py-4 font-black text-white">Place demo order</button></div></>}</div></div>}
</main>}
