export type BarRaidProduct={id:number;legacyProductId:number;slug:string;name:string;category:string;price:number;oldPrice?:number;image:string;code:string;availability:string;description:string;capacity:string;sourceUrl:string};
export const products:BarRaidProduct[]=[
  {
    "id": 50,
    "legacyProductId": 50,
    "slug": "barraid-blue-beer-boot-glass-650-ml-capacity-50",
    "name": "Barraid Blue Beer Boot Glass 650 ml Capacity",
    "category": "Beer Glassware",
    "price": 599,
    "oldPrice": 799,
    "image": "/barraid/products/50.png",
    "code": "BBG_BLUE",
    "availability": "In Stock",
    "description": "Increase the overall drinking experience and is strongly recommended by experts around the globe. Drinking with friends:- Let your un-expecting beer buddy try to figure out the secret on his own. It'll make for a great laugh and he won't forget how to do it the next time. The Solution: How to Drink From a Beer Boot:- The trick to avoiding is to release the bubble slowly. Start drinking from the beer boot with the toe pointed directly away from you. As the bubble moves down the glass, gradually rotate the boot 90 degrees in either direction so that by the time the bubble reaches the toe, the toe is pointing to the right or left. This lessens the pressure, ensuring a smooth drinking experience. Key Features:- • Enjoy your Beer in the most comfortable and stylish 100% Lead-Free,not contain any harmful chemicals Beer Glasses. • Has an elegant look in a wine cabinet and adds to any table's aesthetics with its contemporary design. • These beer glasses are made of thicker glass, particularly on the base. This reinforcement is designed to prevent it from shattering when the drinker slams the glass onto the bar after downing the drink. • The sturdy, solid design of these shot glasses makes ",
    "capacity": "650 ml",
    "sourceUrl": "https://www.barraid.com/Beer-Glass/beer-boot-glass-blue"
  },
  {
    "id": 224,
    "legacyProductId": 224,
    "slug": "barraid-creative-finger-glass-beer-decanter-with-stopper-novelty-wine-bottle-224",
    "name": "BARRAID Creative Finger Glass Beer Decanter with Stopper, Novelty Wine Bottle",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/224.png",
    "code": "MFBD",
    "availability": "2-3 Days",
    "description": "Add a touch of sophistication to your beer-drinking experience with this uniquely designed glass decanter. Crafted in the shape of a hand gesture, this striking vessel is perfect for serving and aerating your favourite brew. The clear glass construction allows you to appreciate the rich colours and clarity of your beer while the innovative design makes for an eye-catching centrepiece at any gathering. The decanter comes with a matching glass stopper to preserve freshness and prevent spills. Its generous capacity is ideal for sharing, and the ergonomic design ensures comfortable pouring. The wide base provides stability, while the smooth finish allows for easy cleaning. This conversation-starting decanter makes an excellent gift for beer enthusiasts and adds a distinctive flair to your home bar collection. Perfect for special occasions or everyday use, this decanter elevates the simple act of serving beer into an artful presentation.",
    "capacity": "See product details",
    "sourceUrl": "https://www.barraid.com/Beer-Glass?product_id=224"
  },
  {
    "id": 54,
    "legacyProductId": 54,
    "slug": "barraid-designer-beer-boot-mug-for-party-pub-bar-gift-for-love-ones-beer-glass-with-750ml--54",
    "name": "Barraid Designer Beer Boot Mug for Party Pub Bar & Gift for love ones Beer Glass With 750ml Capacity",
    "category": "Beer Glassware",
    "price": 599,
    "oldPrice": 1299,
    "image": "/barraid/products/54.png",
    "code": "BBG-GL",
    "availability": "Out Of Stock",
    "description": "Increase the overall drinking experience and is strongly recommended by experts around the globe. Drinking with friends:- Let your un-expecting beer buddy try to figure out the secret on his own. It'll make for a great laugh and he won't forget how to do it the next time. The Solution: How to Drink From a Beer Boot:- The trick to avoiding is to release the bubble slowly. Start drinking from the beer boot with the toe pointed directly away from you. As the bubble moves down the glass, gradually rotate the boot 90 degrees in either direction so that by the time the bubble reaches the toe, the toe is pointing to the right or left. This lessens the pressure, ensuring a smooth drinking experience. Key Features:- -Enjoy your Beer in the most comfortable and stylish 100% Lead-Free,not contain any harmful chemicals Beer Glasses. -Has an elegant look in a wine cabinet and adds to any table's aesthetics with its contemporary design. -These beer glasses are made of thicker glass, particularly on the base. This reinforcement is designed to prevent it from shattering when the drinker slams the glass onto the bar after downing the drink. -The sturdy, solid design of these shot glasses makes them",
    "capacity": "750ml",
    "sourceUrl": "https://www.barraid.com/Beer-Glass/beer-boot-glass-golden"
  },
  {
    "id": 61,
    "legacyProductId": 61,
    "slug": "barraid-designer-beer-boot-mug-61",
    "name": "Barraid Designer Beer Boot Mug",
    "category": "Beer Glassware",
    "price": 599,
    "oldPrice": 1299,
    "image": "/barraid/products/61.png",
    "code": "BBG-SL",
    "availability": "Out Of Stock",
    "description": "Increase the overall drinking experience and is strongly recommended by experts around the globe. Drinking with friends:- Let your un-expecting beer buddy try to figure out the secret on his own. It'll make for a great laugh and he won't forget how to do it the next time. The Solution: How to Drink From a Beer Boot:- The trick to avoiding is to release the bubble slowly. Start drinking from the beer boot with the toe pointed directly away from you. As the bubble moves down the glass, gradually rotate the boot 90 degrees in either direction so that by the time the bubble reaches the toe, the toe is pointing to the right or left. This lessens the pressure, ensuring a smooth drinking experience. Key Features:- -Enjoy your Beer in the most comfortable and stylish 100% Lead-Free,not contain any harmful chemicals Beer Glasses. -Has an elegant look in a wine cabinet and adds to any table's aesthetics with its contemporary design. -These beer glasses are made of thicker glass, particularly on the base. This reinforcement is designed to prevent it from shattering when the drinker slams the glass onto the bar after downing the drink. -The sturdy, solid design of these shot glasses makes them",
    "capacity": "See product details",
    "sourceUrl": "https://www.barraid.com/Beer-Glass/beer-boot-glass-silver"
  },
  {
    "id": 52,
    "legacyProductId": 52,
    "slug": "barraid-designer-dragon-boot-glass-52",
    "name": "Barraid Designer Dragon Boot Glass",
    "category": "Beer Glassware",
    "price": 599,
    "oldPrice": 799,
    "image": "/barraid/products/52.png",
    "code": "BBG-DR",
    "availability": "In Stock",
    "description": "Increase the overall drinking experience and is strongly recommended by experts around the globe. Drinking with friends:- Let your un-expecting beer buddy try to figure out the secret on his own. It'll make for a great laugh and he won't forget how to do it the next time. The Solution: How to Drink From a Beer Boot:- The trick to avoiding is to release the bubble slowly. Start drinking from the beer boot with the toe pointed directly away from you. As the bubble moves down the glass, gradually rotate the boot 90 degrees in either direction so that by the time the bubble reaches the toe, the toe is pointing to the right or left. This lessens the pressure, ensuring a smooth drinking experience. Key Features:- -Enjoy your Beer in the most comfortable and stylish 100% Lead-Free,not contain any harmful chemicals Beer Glasses. -Has an elegant look in a wine cabinet and adds to any table's aesthetics with its contemporary design. -These beer glasses are made of thicker glass, particularly on the base. This reinforcement is designed to prevent it from shattering when the drinker slams the glass onto the bar after downing the drink. -The sturdy, solid design of these shot glasses makes them",
    "capacity": "See product details",
    "sourceUrl": "https://www.barraid.com/Beer-Glass/beer-boot-glass-dragon"
  },
  {
    "id": 53,
    "legacyProductId": 53,
    "slug": "barraid-green-beer-boot-glass-1-litre-capacity-53",
    "name": "Barraid Green Beer Boot Glass 1 litre Capacity",
    "category": "Beer Glassware",
    "price": 599,
    "oldPrice": 1399,
    "image": "/barraid/products/53.png",
    "code": "BBG_GREEN",
    "availability": "Out Of Stock",
    "description": "Strong, Sturdy, High quality and Stylish glass.Extremely Durable and Reusable Glass BARRAID is the leading manufacturer of glassware. SIZE: 5\"x 4\"x 8\" inches. Capacity: 1 Litre Perfect Gift for Beer Lovers.This will be the best gift for Weddings, Birthday, Anniversary and any official events. PERFECT PARTY ITEM - Prepare to have a super fun gathering, party, or dinner. These beer glasses will be a huge addition to the event. Add fun to drinking from BARRAID Boot glass.This giant glass will add fun to the party. CARE & CLEANING - After each use, rinse thoroughly with warm water And allow to air dry, the glass is dishwasher safe.",
    "capacity": "1 litre",
    "sourceUrl": "https://www.barraid.com/Beer-Glass/Beer-Boot-Glass-green"
  },
  {
    "id": 219,
    "legacyProductId": 219,
    "slug": "barraid-world-cup-trophy-shaped-beer-glass-450-ml-capacity-1-glass-crystal-clear-219",
    "name": "BARRAID World Cup Trophy Shaped Beer Glass, 450 ml Capacity, 1 Glass/Crystal Clear",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/219.png",
    "code": "WCBG",
    "availability": "2-3 Days",
    "description": "Elevate your beer-drinking experience with these stunning World Cup-inspired beer glasses. Each glass boasts a unique sculptured design that captures the spirit of football's greatest tournament. With a generous 450ml capacity, these crystal-clear glasses feature a distinctive twisted pattern that not only looks spectacular but also provides an ergonomic grip. Perfect for serving lagers, ales, or any favourite brew, these glasses showcase your beverage with style while maintaining the perfect head. The wide mouth design helps release the beer's aroma, while the sturdy base ensures stability. Whether you're hosting match-day gatherings or simply enjoying a quiet pint, these glasses add a touch of sophistication to any drinking occasion. Their durable construction makes them suitable for regular use, while their eye-catching design makes them conversation starters at parties. Hand washing is recommended to maintain their brilliant clarity and preserve their distinctive appearance.",
    "capacity": "450 ml",
    "sourceUrl": "https://www.barraid.com/Beer-Glass?product_id=219"
  },
  {
    "id": 222,
    "legacyProductId": 222,
    "slug": "barraid-boot-beer-plastic-glass-with-handle-550-ml-clear-glass-western-style-mug-plastic-222",
    "name": "BARRAID Boot Beer Plastic Glass with Handle, 550 ML, Clear Glass Western Style Mug Plastic",
    "category": "Beer Towers",
    "price": 399,
    "oldPrice": 1599,
    "image": "/barraid/products/222.png",
    "code": "BBG550",
    "availability": "In Stock",
    "description": "Add a touch of Western flair to your drinking experience with this uniquely designed boot-shaped beer glass. Standing 16.8 cm tall and 12.7 cm wide, this novelty glass mug features intricate cowboy boot detailing with decorative stitching patterns etched into the crystal-clear glass. The sturdy handle provides a comfortable grip, while the wide opening allows for easy sipping. Perfect for serving your favourite lager, ale, or any cold beverage, this conversation starter holds a generous volume and makes an ideal gift for beer enthusiasts or Western decor lovers. The thick glass construction ensures durability for regular use, while the distinctive boot shape adds a playful element to your barware collection. Hand washing is recommended to maintain its pristine clarity and preserve the detailed design elements.",
    "capacity": "550 ML",
    "sourceUrl": "https://www.barraid.com/Beer-Glass-650ml-and-1Litre?product_id=222"
  },
  {
    "id": 220,
    "legacyProductId": 220,
    "slug": "barraid-boot-shaped-beer-glass-clear-novelty-drinking-glasses-1-piece-550ml-220",
    "name": "BARRAID Boot-Shaped Beer Glass Clear Novelty Drinking Glasses,1 Piece 550ml",
    "category": "Beer Towers",
    "price": 799,
    "oldPrice": 1599,
    "image": "/barraid/products/220.png",
    "code": "BBG550",
    "availability": "In Stock",
    "description": "Add a playful twist to your drinking experience with these uniquely designed boot-shaped beer glasses. Standing approximately 20 cm tall, these novelty glasses feature intricate boot detailing that transforms an ordinary beverage into a conversation starter. Each glass boasts a generous capacity perfect for your favourite lager or ale. The transparent crystal-clear design allows you to appreciate your beverage's colour and clarity, while the sturdy base ensures stability. The glasses' distinctive shape includes textured details reminiscent of traditional German drinking boots, making them ideal for themed parties, special occasions, or as a distinctive addition to your barware collection. The glasses are crafted with attention to detail, featuring a slightly tapered top that helps maintain your beer's head and capture its aroma. These distinctive vessels make excellent gifts for beer enthusiasts or collectors of unique glassware. Hand washing is recommended to preserve the glass's clarity and detailed design features.",
    "capacity": "550ml",
    "sourceUrl": "https://www.barraid.com/Beer-Glass-650ml-and-1Litre?product_id=220"
  },
  {
    "id": 223,
    "legacyProductId": 223,
    "slug": "barraid-boot-shaped-cocktail-glass-300-ml-clear-glass-with-decorative-design-223",
    "name": "BARRAID Boot-Shaped Cocktail Glass, 300 ml, Clear Glass with Decorative Design",
    "category": "Beer Towers",
    "price": 499,
    "oldPrice": 4999,
    "image": "/barraid/products/223.png",
    "code": "BBG300",
    "availability": "In Stock",
    "description": "Add a whimsical touch to your drinking experience with this delightfully quirky boot-shaped beer glass. Perfect for serving your favourite beverages in style, this unique glass features a distinctive boot design that holds approximately 300 ml of liquid. The crystal-clear glass construction allows you to showcase the colour and clarity of your drinks while the wide opening accommodates garnishes like citrus slices and fresh herbs. The sturdy base provides excellent stability, whilst the thick glass walls help maintain your drink's temperature. Ideal for serving beer, cocktails, or creative mocktails, this conversation-starting glass is sure to be the highlight of your next gathering. The glass is dishwasher safe for easy cleaning, though hand washing is recommended to maintain its pristine appearance. A brilliant addition to any home bar or restaurant collection, this boot-shaped glass transforms ordinary drinks into memorable experiences.",
    "capacity": "300 ml",
    "sourceUrl": "https://www.barraid.com/Beer-Glass-650ml-and-1Litre?product_id=223"
  },
  {
    "id": 221,
    "legacyProductId": 221,
    "slug": "barraid-glass-beer-boot-580-ml-capacity-traditional-das-boot-style-drinking-glass-221",
    "name": "BARRAID Glass Beer Boot, 580 ml Capacity, Traditional Das Boot Style Drinking Glass",
    "category": "Beer Towers",
    "price": 799,
    "oldPrice": 1599,
    "image": "/barraid/products/221.png",
    "code": "BBG580",
    "availability": "In Stock",
    "description": "Increase the overall drinking experience and is strongly recommended by experts around the globe. Drinking with friends:- Let your un-expecting beer buddy try to figure out the secret on his own. It'll make for a great laugh and he won't forget how to do it the next time. The Solution: How to Drink From a Beer Boot:- The trick to avoiding is to release the bubble slowly. Start drinking from the beer boot with the toe pointed directly away from you. As the bubble moves down the glass, gradually rotate the boot 90 degrees in either direction so that by the time the bubble reaches the toe, the toe is pointing to the right or left. This lessens the pressure, ensuring a smooth drinking experience. Key Features:- Enjoy your Beer in the most comfortable and stylish 100% Lead-Free,not contain any harmful chemicals Beer Glasses. Has an elegant look in a wine cabinet and adds to any table's aesthetics with its contemporary design. These beer glasses are made of thicker glass, particularly on the base. This reinforcement is designed to prevent it from shattering when the drinker slams the glass onto the bar after downing the drink. The sturdy, solid design of these shot glasses makes them rel",
    "capacity": "580 ml",
    "sourceUrl": "https://www.barraid.com/Beer-Glass-650ml-and-1Litre?product_id=221"
  },
  {
    "id": 234,
    "legacyProductId": 234,
    "slug": "barraid-beer-tower-beverage-dispenser-3-litre-capacity-tabletop-drink-dispenser-with-dual--234",
    "name": "BARRAID Beer Tower Beverage Dispenser, 3 Litre Capacity, Tabletop Drink Dispenser with Dual Taps, (BLUE)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/234.png",
    "code": "SD398",
    "availability": "Out Of Stock",
    "description": "Elevate your entertaining experience with this sleek and stylish beverage dispenser, perfect for serving cold drinks at parties, gatherings, or casual get-togethers. The tall, transparent tower design showcases your beverages beautifully while keeping them fresh and readily accessible. Featuring dual taps for convenient dispensing, this 3-litre capacity dispenser allows multiple guests to serve themselves simultaneously. The sturdy base provides excellent stability, while the removable lid makes refilling and cleaning a breeze. Ideal for serving beer, cocktails, juices, or any cold beverage of your choice, this dispenser combines practicality with contemporary aesthetics. The high-quality construction ensures durability, whilst the clear vessel lets you monitor beverage levels easily. Perfect for home bars, outdoor events, or special occasions, this dispenser adds a touch of sophistication to your beverage service setup.",
    "capacity": "3 Litre",
    "sourceUrl": "https://www.barraid.com/BEER-TOWER-WITH-LED-LIGHTS?product_id=234"
  },
  {
    "id": 232,
    "legacyProductId": 232,
    "slug": "barraid-beer-tower-beverage-dispenser-3-litre-capacity-tabletop-drink-dispenser-with-dual--232",
    "name": "BARRAID Beer Tower Beverage Dispenser, 3 Litre Capacity, Tabletop Drink Dispenser with Dual Taps, (RED)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/232.png",
    "code": "SD398",
    "availability": "Out Of Stock",
    "description": "Elevate your entertaining experience with this sleek and stylish beverage dispenser, perfect for serving cold drinks at parties, gatherings, or casual get-togethers. The tall, transparent tower design showcases your beverages beautifully while keeping them fresh and readily accessible. Featuring dual taps for convenient dispensing, this 3-litre capacity dispenser allows multiple guests to serve themselves simultaneously. The sturdy base provides excellent stability, while the removable lid makes refilling and cleaning a breeze. Ideal for serving beer, cocktails, juices, or any cold beverage of your choice, this dispenser combines practicality with contemporary aesthetics. The high-quality construction ensures durability, whilst the clear vessel lets you monitor beverage levels easily. Perfect for home bars, outdoor events, or special occasions, this dispenser adds a touch of sophistication to your beverage service setup.",
    "capacity": "3 Litre",
    "sourceUrl": "https://www.barraid.com/BEER-TOWER-WITH-LED-LIGHTS?product_id=232"
  },
  {
    "id": 231,
    "legacyProductId": 231,
    "slug": "barraid-beer-tower-beverage-dispenser-3-litre-capacity-tabletop-drink-dispenser-with-dual--231",
    "name": "BARRAID Beer Tower Beverage Dispenser, 3 Litre Capacity, Tabletop Drink Dispenser with Dual Taps, (Silver)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/231.png",
    "code": "SD398",
    "availability": "Out Of Stock",
    "description": "Elevate your entertaining experience with this sleek and stylish beverage dispenser, perfect for serving cold drinks at parties, gatherings, or casual get-togethers. The tall, transparent tower design showcases your beverages beautifully while keeping them fresh and readily accessible. Featuring dual taps for convenient dispensing, this 3-litre capacity dispenser allows multiple guests to serve themselves simultaneously. The sturdy base provides excellent stability, while the removable lid makes refilling and cleaning a breeze. Ideal for serving beer, cocktails, juices, or any cold beverage of your choice, this dispenser combines practicality with contemporary aesthetics. The high-quality construction ensures durability, whilst the clear vessel lets you monitor beverage levels easily. Perfect for home bars, outdoor events, or special occasions, this dispenser adds a touch of sophistication to your beverage service setup.",
    "capacity": "3 Litre",
    "sourceUrl": "https://www.barraid.com/BEER-TOWER-WITH-LED-LIGHTS?product_id=231"
  },
  {
    "id": 233,
    "legacyProductId": 233,
    "slug": "barraid-beer-tower-beverage-dispenser-3-litre-capacity-tabletop-drink-dispenser-with-dual--233",
    "name": "BARRAID Beer Tower Beverage Dispenser, 3 Litre Capacity, Tabletop Drink Dispenser with Dual Taps, (YELLOW)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/233.png",
    "code": "SD398",
    "availability": "2-3 Days",
    "description": "Elevate your entertaining experience with this sleek and stylish beverage dispenser, perfect for serving cold drinks at parties, gatherings, or casual get-togethers. The tall, transparent tower design showcases your beverages beautifully while keeping them fresh and readily accessible. Featuring dual taps for convenient dispensing, this 3-litre capacity dispenser allows multiple guests to serve themselves simultaneously. The sturdy base provides excellent stability, while the removable lid makes refilling and cleaning a breeze. Ideal for serving beer, cocktails, juices, or any cold beverage of your choice, this dispenser combines practicality with contemporary aesthetics. The high-quality construction ensures durability, whilst the clear vessel lets you monitor beverage levels easily. Perfect for home bars, outdoor events, or special occasions, this dispenser adds a touch of sophistication to your beverage service setup.",
    "capacity": "3 Litre",
    "sourceUrl": "https://www.barraid.com/BEER-TOWER-WITH-LED-LIGHTS?product_id=233"
  },
  {
    "id": 225,
    "legacyProductId": 225,
    "slug": "barraid-beer-tower-beverage-dispenser-3-litre-tabletop-draft-drink-dispenser-blue-225",
    "name": "BARRAID Beer Tower Beverage Dispenser, 3 Litre, Tabletop Draft Drink Dispenser (Blue)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/225.png",
    "code": "SD198",
    "availability": "2-3 Days",
    "description": "Elevate your parties and gatherings with this sleek 3-litre beverage dispenser, featuring a striking green base and transparent cylinder design. The tall, slender tower configuration adds a modern touch to any setting while maximising your counter or table space. The durable construction includes a precise dispensing tap that provides smooth, controlled pouring without drips or spills. Perfect for serving cold drinks, juices, or cocktails, this dispenser keeps beverages readily accessible for your guests. The wide-mouth top allows for easy filling and cleaning, while the clear container lets you monitor beverage levels at a glance. The stable base ensures secure placement, making it ideal for both indoor and outdoor entertaining. Whether hosting a casual get-together or a formal event, this practical dispenser combines style with functionality to keep your beverages flowing and your guests refreshed.",
    "capacity": "3 Litre",
    "sourceUrl": "https://www.barraid.com/BEER-TOWER-WITH-LED-LIGHTS?product_id=225"
  },
  {
    "id": 228,
    "legacyProductId": 228,
    "slug": "barraid-beer-tower-beverage-dispenser-3-litre-tabletop-draft-drink-dispenser-golden-228",
    "name": "BARRAID Beer Tower Beverage Dispenser, 3 Litre, Tabletop Draft Drink Dispenser (Golden)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/228.png",
    "code": "SD198",
    "availability": "2-3 Days",
    "description": "Elevate your parties and gatherings with this sleek 3-litre beverage dispenser, featuring a striking green base and transparent cylinder design. The tall, slender tower configuration adds a modern touch to any setting while maximising your counter or table space. The durable construction includes a precise dispensing tap that provides smooth, controlled pouring without drips or spills. Perfect for serving cold drinks, juices, or cocktails, this dispenser keeps beverages readily accessible for your guests. The wide-mouth top allows for easy filling and cleaning, while the clear container lets you monitor beverage levels at a glance. The stable base ensures secure placement, making it ideal for both indoor and outdoor entertaining. Whether hosting a casual get-together or a formal event, this practical dispenser combines style with functionality to keep your beverages flowing and your guests refreshed.",
    "capacity": "3 Litre",
    "sourceUrl": "https://www.barraid.com/BEER-TOWER-WITH-LED-LIGHTS?product_id=228"
  },
  {
    "id": 227,
    "legacyProductId": 227,
    "slug": "barraid-beer-tower-beverage-dispenser-3-litre-tabletop-draft-drink-dispenser-green-227",
    "name": "BARRAID Beer Tower Beverage Dispenser, 3 Litre, Tabletop Draft Drink Dispenser (Green)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/227.png",
    "code": "SD198",
    "availability": "2-3 Days",
    "description": "Elevate your parties and gatherings with this sleek 3-litre beverage dispenser, featuring a striking green base and transparent cylinder design. The tall, slender tower configuration adds a modern touch to any setting while maximising your counter or table space. The durable construction includes a precise dispensing tap that provides smooth, controlled pouring without drips or spills. Perfect for serving cold drinks, juices, or cocktails, this dispenser keeps beverages readily accessible for your guests. The wide-mouth top allows for easy filling and cleaning, while the clear container lets you monitor beverage levels at a glance. The stable base ensures secure placement, making it ideal for both indoor and outdoor entertaining. Whether hosting a casual get-together or a formal event, this practical dispenser combines style with functionality to keep your beverages flowing and your guests refreshed.",
    "capacity": "3 Litre",
    "sourceUrl": "https://www.barraid.com/BEER-TOWER-WITH-LED-LIGHTS?product_id=227"
  },
  {
    "id": 229,
    "legacyProductId": 229,
    "slug": "barraid-beer-tower-beverage-dispenser-3-litre-tabletop-draft-drink-dispenser-red-229",
    "name": "BARRAID Beer Tower Beverage Dispenser, 3 Litre, Tabletop Draft Drink Dispenser (Red)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/229.png",
    "code": "SD198",
    "availability": "2-3 Days",
    "description": "Elevate your parties and gatherings with this sleek 3-litre beverage dispenser, featuring a striking green base and transparent cylinder design. The tall, slender tower configuration adds a modern touch to any setting while maximising your counter or table space. The durable construction includes a precise dispensing tap that provides smooth, controlled pouring without drips or spills. Perfect for serving cold drinks, juices, or cocktails, this dispenser keeps beverages readily accessible for your guests. The wide-mouth top allows for easy filling and cleaning, while the clear container lets you monitor beverage levels at a glance. The stable base ensures secure placement, making it ideal for both indoor and outdoor entertaining. Whether hosting a casual get-together or a formal event, this practical dispenser combines style with functionality to keep your beverages flowing and your guests refreshed.",
    "capacity": "3 Litre",
    "sourceUrl": "https://www.barraid.com/BEER-TOWER-WITH-LED-LIGHTS?product_id=229"
  },
  {
    "id": 230,
    "legacyProductId": 230,
    "slug": "barraid-beer-tower-beverage-dispenser-3-litre-tabletop-draft-drink-dispenser-silver-230",
    "name": "BARRAID Beer Tower Beverage Dispenser, 3 Litre, Tabletop Draft Drink Dispenser (Silver)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/230.png",
    "code": "SD198",
    "availability": "2-3 Days",
    "description": "Elevate your parties and gatherings with this sleek 3-litre beverage dispenser, featuring a striking green base and transparent cylinder design. The tall, slender tower configuration adds a modern touch to any setting while maximising your counter or table space. The durable construction includes a precise dispensing tap that provides smooth, controlled pouring without drips or spills. Perfect for serving cold drinks, juices, or cocktails, this dispenser keeps beverages readily accessible for your guests. The wide-mouth top allows for easy filling and cleaning, while the clear container lets you monitor beverage levels at a glance. The stable base ensures secure placement, making it ideal for both indoor and outdoor entertaining. Whether hosting a casual get-together or a formal event, this practical dispenser combines style with functionality to keep your beverages flowing and your guests refreshed.",
    "capacity": "3 Litre",
    "sourceUrl": "https://www.barraid.com/BEER-TOWER-WITH-LED-LIGHTS?product_id=230"
  },
  {
    "id": 104,
    "legacyProductId": 104,
    "slug": "barraid-double-gas-pump-liquor-dispenser-capacity-900-ml-104",
    "name": "Barraid Double Gas Pump Liquor Dispenser Capacity 900 ML",
    "category": "Liquor Dispensers",
    "price": 1999,
    "oldPrice": 2799,
    "image": "/barraid/products/104.png",
    "code": "DGPLD",
    "availability": "Out Of Stock",
    "description": "This new charming retro liquor dispenser is sure to be an instant conversation starter! Featuring a unique design that looks like an old-fashioned gas pump, the Gas Pump Liquor Dispenser has a silver-plated body that is tarnish resistant and a durable, see-through plastic reservoir with measurements for you to monitor drink levels at all times. Pump up to 450ml each with two your different favorite drink and fire the Wild West style pistol at will. A fantastic item for parties and celebrations, you can set your own \"fuel\" prices today and let your guests pour away!",
    "capacity": "900 ML",
    "sourceUrl": "https://www.barraid.com/double-gas-pump-liquor-dispenser"
  },
  {
    "id": 76,
    "legacyProductId": 76,
    "slug": "bonny-boy-silver-squrae-black-liquor-dispeser-500-ml-capacity-76",
    "name": "BONNY BOY SILVER SQURAE BLACK LIQUOR DISPESER 500 ML CAPACITY",
    "category": "Liquor Dispensers",
    "price": 1999,
    "oldPrice": 1999,
    "image": "/barraid/products/76.png",
    "code": "BBSQS",
    "availability": "Out Of Stock",
    "description": "Bonny Boy Liquor Dispenser Pouring Liquor From Its Bottle Every Time You Make A Drink, Is So Old Fashioned And Boring As Well. So Buy This Bonny-Boy Liquor-Dispenser To Make Your Drink Serving Experience Fun And More Enjoyable. This Funny Yet Cute Liquor Dispenser Takes Its Inspiration . Just Fill Its Bottom Container With Your Favorite Drink And It Will Be Ready To Serve It By A Single Push Button Operation. Place It In Your Home Bar Or Kitchen Top For Cocktail Parties. Your Guests Are Going To Love It. This Easy To Use Leisure Liquor Dispenser Runs On 2 Aa Batteries.. In Stock And Ready To Ship. Features Modeled After Famous Manneken Pis Sculpture In Brussels Push Button Operation Unique Gift Idea Uses 2 Aa Batteries (Not Included) Specs Dimensions: 3 1/2\"W X 12 1/2\"H X 3 1/2\"D Capacity: 16 Oz",
    "capacity": "500 ML",
    "sourceUrl": "https://www.barraid.com/Bonny-Boy-Square-Silver"
  },
  {
    "id": 73,
    "legacyProductId": 73,
    "slug": "barraid-santa-clause-round-beer-liquor-dispenser-capacity-500-ml-for-christmas-gift-73",
    "name": "Barraid Santa Clause Round Beer Liquor Dispenser Capacity 500 ML for Christmas Gift",
    "category": "Liquor Dispensers",
    "price": 1599,
    "oldPrice": 2199,
    "image": "/barraid/products/73.png",
    "code": "SCR",
    "availability": "In Stock",
    "description": "Push Button Operation Perfect Gift for Beer Lovers Easy to Use Leisure Liquor Dispenser Runs on 2 AA Batteries Great for Parties, Outdoors, and Around the Home Capacity: 16 oz",
    "capacity": "500 ML",
    "sourceUrl": "https://www.barraid.com/santa-claus-with-round-jar"
  },
  {
    "id": 58,
    "legacyProductId": 58,
    "slug": "barraid-gas-pump-liquor-wine-dispenser-58",
    "name": "Barraid Gas Pump Liquor,Wine Dispenser",
    "category": "Liquor Dispensers",
    "price": 1799,
    "oldPrice": 1599,
    "image": "/barraid/products/58.png",
    "code": "RCPDGPLD",
    "availability": "Out Of Stock",
    "description": "Red Chrome Plated ABS Plastic Body and Two 17\" Gas Hoses Wine Dispenser Tarnish Resistant and Durable See Through Reservoir. Features Dual Chambers that Hold Nearly 750 ML Each Size 19\"x7\"x6\"",
    "capacity": "See product details",
    "sourceUrl": "https://www.barraid.com/red-chrome-dispenser"
  },
  {
    "id": 102,
    "legacyProductId": 102,
    "slug": "barraid-double-gas-pump-liquor-dispenser-black-chrome-plated-1500-ml-capacity-102",
    "name": "Barraid Double Gas Pump Liquor Dispenser Black Chrome Plated 1500 ML Capacity",
    "category": "Liquor Dispensers",
    "price": 1599,
    "image": "/barraid/products/102.png",
    "code": "BCPDGPLD",
    "availability": "Out Of Stock",
    "description": "This new charming retro liquor dispenser is sure to be an instant conversation starter! Featuring a unique design that looks like an old-fashioned gas pump, the Gas Pump Liquor Dispenser has a red chrome plated body that is tarnish resistant and a durable, see-through plastic reservoir with measurements for you to monitor drink levels at all times. Pump up to 750 ml each with two your different favourite drink and fire the Wild West style pistol at will. A fantastic item for parties and celebrations, you can set your own \"fuel\" prices today and let your guests pour away!. This Dual chambered gas pump liquor dispenser measures 19\"x7\"x6\". Arrives gift packaged. Each side holds 750 ML Liquor and has two 17\" gas hoses.",
    "capacity": "1500 ML",
    "sourceUrl": "https://www.barraid.com/black-chrome-dispenser"
  },
  {
    "id": 72,
    "legacyProductId": 72,
    "slug": "barraid-singapore-lion-liquor-dispenser-red-round-shape-with-white-jar-500-ml-capacity-72",
    "name": "Barraid Singapore Lion Liquor Dispenser Red Round Shape with White Jar 500 ML Capacity",
    "category": "Liquor Dispensers",
    "price": 1599,
    "oldPrice": 2999,
    "image": "/barraid/products/72.png",
    "code": "SLRRW",
    "availability": "In Stock",
    "description": "Push Button Operation Liquor Decanter Easy to Use Leisure Liquor Dispenser Runs on 2 AA Batteries Its Great Fun/Unique item for Liquor Lovers..! Capacity: 16 oz",
    "capacity": "500 ML",
    "sourceUrl": "https://www.barraid.com/Singapore-Lion-Red"
  },
  {
    "id": 66,
    "legacyProductId": 66,
    "slug": "barraid-double-gas-pump-liquor-dispenser-silver-chrome-1500-ml-capacity-66",
    "name": "Barraid Double Gas Pump Liquor Dispenser Silver Chrome 1500 ML Capacity",
    "category": "Liquor Dispensers",
    "price": 1599,
    "oldPrice": 3999,
    "image": "/barraid/products/66.png",
    "code": "SCPDGPLD",
    "availability": "Out Of Stock",
    "description": "Uses: Liquor dispenser can suitable for red wine ,beer, and widely used in bars, hotels, teahouses, KTV, family and soon. Material : Chrome-plated ABS/Metal/rubber/plastic Capacity: 1500ML Size: 19\"cm x 7\"cm x 6\"cm, Faucet long 55cm CUSTOMER FEEDBACK: We at 'BARRAID' are working hard to make and present the best product.We are looking to have good and genuine feedback that might help others",
    "capacity": "1500 ML",
    "sourceUrl": "https://www.barraid.com/Liquor-Dispenser/silver-chrome-dispenser"
  },
  {
    "id": 77,
    "legacyProductId": 77,
    "slug": "barraid-santa-clause-square-beer-liquor-dispenser-capacity-500-ml-for-christmas-gift-77",
    "name": "Barraid Santa Clause Square Beer Liquor Dispenser Capacity 500 ML for Christmas Gift",
    "category": "Liquor Dispensers",
    "price": 1599,
    "oldPrice": 2299,
    "image": "/barraid/products/77.png",
    "code": "SCSQ",
    "availability": "Out Of Stock",
    "description": "Liquor dispenser Beer Dispenser Decanter Liquor Decanter Wine Decanter",
    "capacity": "500 ML",
    "sourceUrl": "https://www.barraid.com/Liquor-Dispenser/Santa-Claus-with-square-jar"
  },
  {
    "id": 84,
    "legacyProductId": 84,
    "slug": "barraid-singapore-lion-liquor-dispenser-silver-round-shape-with-black-jar-500-ml-capacity-84",
    "name": "Barraid Singapore Lion Liquor Dispenser Silver Round Shape with Black Jar 500 ML Capacity",
    "category": "Liquor Dispensers",
    "price": 1599,
    "oldPrice": 2999,
    "image": "/barraid/products/84.png",
    "code": "SLSRB",
    "availability": "In Stock",
    "description": "Push Button Operation Liquor Decanter Easy to Use Leisure Liquor Dispenser Runs on 2 AA Batteries Its Great Fun/Unique item for Liquor Lovers..! Capacity: 16 oz Barraid Singapore Lion Silver Liquor Dispenser - Pouring liquor from its bottle every time you make a drink, is so old fashioned and boring as well. So buy this Barraid Singapore Lion Silver Liquor Dispenser to make your drink serving experience fun and more enjoyable. Just fill its bottom container with your favorite drink and it will be ready to serve it by a single push button operation. Place it in your home bar or kitchen top for cocktail parties. Your guests are going to love it. This easy to use leisure liquor dispenser runs on 2 AA batteries .. • In stock and ready to ship. Features • Push button operation • Unique gift idea • Uses 2 AA Batteries (not included) Specs • Dimensions: 3 1/2\"W x 12 1/2\"H x 3 1/2\"D • Capacity: 16 oz",
    "capacity": "500 ML",
    "sourceUrl": "https://www.barraid.com/Liquor-Dispenser/Singapore-Lion-Silver"
  },
  {
    "id": 57,
    "legacyProductId": 57,
    "slug": "bonny-boy-liquor-beer-dispenser-57",
    "name": "BONNY BOY LIQUOR/BEER DISPENSER",
    "category": "Liquor Dispensers",
    "price": 1599,
    "oldPrice": 1999,
    "image": "/barraid/products/57.png",
    "code": "BBSQB",
    "availability": "In Stock",
    "description": "Bonny Boy Liquor Dispenser Pouring Liquor From Its Bottle Every Time You Make A Drink, Is So Old Fashioned And Boring As Well. So Buy This Bonny-Boy Liquor-Dispenser To Make Your Drink Serving Experience Fun And More Enjoyable. This Funny Yet Cute Liquor Dispenser Takes Its Inspiration . Just Fill Its Bottom Container With Your Favorite Drink And It Will Be Ready To Serve It By A Single Push Button Operation. Place It In Your Home Bar Or Kitchen Top For Cocktail Parties. Your Guests Are Going To Love It. This Easy To Use Leisure Liquor Dispenser Runs On 2 Aa Batteries.. In Stock And Ready To Ship. Features Modeled After Famous Manneken Pis Sculpture In Brussels Push Button Operation Unique Gift Idea Uses 2 Aa Batteries (Not Included) Specs Dimensions: 3 1/2\"W X 12 1/2\"H X 3 1/2\"D Capacity: 16 Oz",
    "capacity": "See product details",
    "sourceUrl": "https://www.barraid.com/Bonny-Boy-Liquor-Dispenser/Bonny-Boy-Square-Black"
  },
  {
    "id": 64,
    "legacyProductId": 64,
    "slug": "bonny-boy-square-golden-liquor-dispenser-500-ml-capacity-64",
    "name": "Bonny Boy Square Golden Liquor Dispenser 500 ml Capacity",
    "category": "Liquor Dispensers",
    "price": 1599,
    "oldPrice": 1999,
    "image": "/barraid/products/64.png",
    "code": "BBSQG",
    "availability": "In Stock",
    "description": "Bar accessories Liquor dispenser Decanter Great for Parties, Outdoors, and Around the Home Capacity: 16 oz",
    "capacity": "500 ml",
    "sourceUrl": "https://www.barraid.com/Bonny-Boy-Liquor-Dispenser/Bonny-Boy-Square-Golden"
  },
  {
    "id": 65,
    "legacyProductId": 65,
    "slug": "barraid-singapore-lion-liquor-dispenser-white-round-shape-with-black-jar-500-ml-capacity-65",
    "name": "Barraid Singapore Lion Liquor Dispenser White Round Shape with Black Jar 500 ML Capacity",
    "category": "Liquor Dispensers",
    "price": 1599,
    "oldPrice": 1599,
    "image": "/barraid/products/65.png",
    "code": "SLWRB",
    "availability": "In Stock",
    "description": "Push Button Operation Liquor Decanter Easy to Use Leisure Liquor Dispenser Runs on 2 AA Batteries Its Great Fun/Unique item for Liquor Lovers..! Capacity: 16 oz",
    "capacity": "500 ML",
    "sourceUrl": "https://www.barraid.com/Singapore-Lion-Liquor-Dispenser/Singapore-Lion-White"
  },
  {
    "id": 196,
    "legacyProductId": 196,
    "slug": "barraid-large-3000-ml-3-l-capacity-world-cup-tower-dispenser-decanter-for-beer-whisky-wine-196",
    "name": "BARRAID Large 3000 ml, 3 L Capacity World Cup Tower/Dispenser/Decanter for Beer/Whisky/Wine with Sparkling LED Lights, Multicolour (Yellow)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/196.png",
    "code": "WBTC-1",
    "availability": "In Stock",
    "description": "Elevate your party or home bar experience with this striking 3000ml (3L) capacity World Cup Tower Dispenser from BARRAID. Crafted with a sleek and stylish design, this decanter comes in four vibrant colours - blue, red, golden, and yellow. The transparent glass globe allows you to showcase your favourite beverages, be it beer, whisky, wine, or any other drink. With its wide base and tapered top, it ensures a steady pour every time. The built-in sparkling LED lights add a festive touch, creating an inviting ambiance. Perfect for gatherings, parties, or simply enjoying a drink at home, this dispenser is sure to impress your guests. Its large capacity makes it ideal for serving multiple people without frequent refills. Elevate your hosting game with this eye-catching and functional World Cup Tower Dispenser.",
    "capacity": "3000 ml",
    "sourceUrl": "https://www.barraid.com/index.php?route=product/product&product_id=196"
  },
  {
    "id": 197,
    "legacyProductId": 197,
    "slug": "barraid-amazing-cup-dispenser-liquor-beer-dispenser-decanter-for-beer-whisky-wine-with-spa-197",
    "name": "BARRAID Amazing Cup Dispenser Liquor/Beer Dispenser/Decanter for Beer/Whisky/Wine with Sparkling Multi Colored LED Lights ICE Tube (Capacity 3000 ml) (Blue)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/197.png",
    "code": "CBT-798",
    "availability": "In Stock",
    "description": "The BARRAID Amazing Cup Dispenser is designed to take your beverage-serving experience to the next level. With a large 3000 ml capacity, this dispenser is perfect for social events, ensuring you and your guests can enjoy drinks without the hassle of frequent refills. This multifunctional dispenser accommodates a wide variety of drinks, including beer, whisky, wine, and cocktails, adding versatility to your hosting capabilities. Adding to the visual appeal, the dispenser is equipped with multi-colored LED lights that create a sparkling, party-ready ambiance. The stunning golden finish brings elegance to any setting, while the ice tube feature ensures your drinks stay cold without getting diluted. With its easy-to-use design and spill-free pouring mechanism, this dispenser is convenient for both serving and cleaning. The BARRAID Amazing Cup Dispenser makes an impressive gift for friends, family, and colleagues who love to host gatherings or simply enjoy a quality drink. Whether for a holiday, housewarming, or any special occasion, this dispenser is a unique, functional, and stylish choice for any bar enthusiast",
    "capacity": "3000 ml",
    "sourceUrl": "https://www.barraid.com/index.php?route=product/product&product_id=197"
  },
  {
    "id": 198,
    "legacyProductId": 198,
    "slug": "barraid-amazing-cup-dispenser-liquor-beer-dispenser-decanter-for-beer-whisky-wine-with-spa-198",
    "name": "BARRAID Amazing Cup Dispenser Liquor/Beer Dispenser/Decanter for Beer/Whisky/Wine with Sparkling Multi Colored LED Lights ICE Tube (Capacity 3000 ml) (Golden)",
    "category": "Beer Towers",
    "price": 3699,
    "oldPrice": 4999,
    "image": "/barraid/products/198.png",
    "code": "CBT-798",
    "availability": "In Stock",
    "description": "The BARRAID Amazing Cup Dispenser is designed to take your beverage-serving experience to the next level. With a large 3000 ml capacity, this dispenser is perfect for social events, ensuring you and your guests can enjoy drinks without the hassle of frequent refills. This multifunctional dispenser accommodates a wide variety of drinks, including beer, whisky, wine, and cocktails, adding versatility to your hosting capabilities. Adding to the visual appeal, the dispenser is equipped with multi-colored LED lights that create a sparkling, party-ready ambiance. The stunning golden finish brings elegance to any setting, while the ice tube feature ensures your drinks stay cold without getting diluted. With its easy-to-use design and spill-free pouring mechanism, this dispenser is convenient for both serving and cleaning. The BARRAID Amazing Cup Dispenser makes an impressive gift for friends, family, and colleagues who love to host gatherings or simply enjoy a quality drink. Whether for a holiday, housewarming, or any special occasion, this dispenser is a unique, functional, and stylish choice for any bar enthusiast.",
    "capacity": "3000 ml",
    "sourceUrl": "https://www.barraid.com/index.php?route=product/product&product_id=198"
  },
  {
    "id": 199,
    "legacyProductId": 199,
    "slug": "barraid-amazing-cup-dispenser-liquor-beer-dispenser-decanter-for-beer-whisky-wine-with-spa-199",
    "name": "BARRAID Amazing Cup Dispenser Liquor/Beer Dispenser/Decanter for Beer/Whisky/Wine with Sparkling Multi Colored LED Lights ICE Tube (Capacity 3000 ml) (RED)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/199.png",
    "code": "CBT-798",
    "availability": "In Stock",
    "description": "The BARRAID Amazing Cup Dispenser is designed to take your beverage-serving experience to the next level. With a large 3000 ml capacity, this dispenser is perfect for social events, ensuring you and your guests can enjoy drinks without the hassle of frequent refills. This multifunctional dispenser accommodates a wide variety of drinks, including beer, whisky, wine, and cocktails, adding versatility to your hosting capabilities. Adding to the visual appeal, the dispenser is equipped with multi-colored LED lights that create a sparkling, party-ready ambiance. The stunning golden finish brings elegance to any setting, while the ice tube feature ensures your drinks stay cold without getting diluted. With its easy-to-use design and spill-free pouring mechanism, this dispenser is convenient for both serving and cleaning. The BARRAID Amazing Cup Dispenser makes an impressive gift for friends, family, and colleagues who love to host gatherings or simply enjoy a quality drink. Whether for a holiday, housewarming, or any special occasion, this dispenser is a unique, functional, and stylish choice for any bar enthusiast.",
    "capacity": "3000 ml",
    "sourceUrl": "https://www.barraid.com/index.php?route=product/product&product_id=199"
  },
  {
    "id": 200,
    "legacyProductId": 200,
    "slug": "barraid-amazing-cup-dispenser-liquor-beer-dispenser-decanter-for-beer-whisky-wine-with-spa-200",
    "name": "BARRAID Amazing Cup Dispenser Liquor/Beer Dispenser/Decanter for Beer/Whisky/Wine with Sparkling Multi Colored LED Lights ICE Tube (Capacity 3000 ml) (Yellow)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/200.png",
    "code": "CBT-798",
    "availability": "In Stock",
    "description": "The BARRAID Amazing Cup Dispenser is designed to take your beverage-serving experience to the next level. With a large 3000 ml capacity, this dispenser is perfect for social events, ensuring you and your guests can enjoy drinks without the hassle of frequent refills. This multifunctional dispenser accommodates a wide variety of drinks, including beer, whisky, wine, and cocktails, adding versatility to your hosting capabilities. Adding to the visual appeal, the dispenser is equipped with multi-colored LED lights that create a sparkling, party-ready ambiance. The stunning golden finish brings elegance to any setting, while the ice tube feature ensures your drinks stay cold without getting diluted. With its easy-to-use design and spill-free pouring mechanism, this dispenser is convenient for both serving and cleaning. The BARRAID Amazing Cup Dispenser makes an impressive gift for friends, family, and colleagues who love to host gatherings or simply enjoy a quality drink. Whether for a holiday, housewarming, or any special occasion, this dispenser is a unique, functional, and stylish choice for any bar enthusiast",
    "capacity": "3000 ml",
    "sourceUrl": "https://www.barraid.com/index.php?route=product/product&product_id=200"
  },
  {
    "id": 206,
    "legacyProductId": 206,
    "slug": "barraid-3l-draft-beer-tower-with-sparkling-light-ice-tube-beverage-dispenser-for-beer-liqu-206",
    "name": "BARRAID 3L Draft Beer Tower with Sparkling Light Ice Tube – Beverage Dispenser for Beer, Liquor, and Drinks 3000ml Capacity, Green",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/206.png",
    "code": "BT-S9",
    "availability": "In Stock",
    "description": "The BARRAID 3L Draft Beer Tower with Sparkling Light Ice Tube brings a unique and stylish touch to any gathering. With a generous 3L (3000ml) capacity, this beverage dispenser is designed to keep your favorite drinks cool and fresh without diluting them. Its built-in ice tube includes sparkling lights, adding a fun, ambient glow that enhances the atmosphere. Constructed from durable, BPA-free materials, the tower boasts a sleek green design that fits perfectly in both casual and upscale settings. The easy-to-use tap ensures smooth, controlled pouring, reducing spills and making it a great choice for parties, game nights, and other social events. Ideal for dispensing beer, cocktails, soda, juice, and other cold drinks, this versatile drink tower is perfect for anyone looking to elevate their hosting experience. Whether for home entertaining or professional use, the BARRAID 3L Draft Beer Tower offers functionality, style, and convenience all in one.",
    "capacity": "3L",
    "sourceUrl": "https://www.barraid.com/index.php?route=product/product&product_id=206"
  },
  {
    "id": 207,
    "legacyProductId": 207,
    "slug": "barraid-3l-draft-beer-tower-with-sparkling-light-ice-tube-beverage-dispenser-for-beer-liqu-207",
    "name": "BARRAID 3L Draft Beer Tower with Sparkling Light Ice Tube – Beverage Dispenser for Beer, Liquor, and Drinks – 3000ml Capacity, NAVY BLUE",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/207.png",
    "code": "BT-S9",
    "availability": "In Stock",
    "description": "The BARRAID 3L Draft Beer Tower with Sparkling Light Ice Tube brings a unique and stylish touch to any gathering. With a generous 3L (3000ml) capacity, this beverage dispenser is designed to keep your favorite drinks cool and fresh without diluting them. Its built-in ice tube includes sparkling lights, adding a fun, ambient glow that enhances the atmosphere. Constructed from durable, BPA-free materials, the tower boasts a sleek green design that fits perfectly in both casual and upscale settings. The easy-to-use tap ensures smooth, controlled pouring, reducing spills and making it a great choice for parties, game nights, and other social events. Ideal for dispensing beer, cocktails, soda, juice, and other cold drinks, this versatile drink tower is perfect for anyone looking to elevate their hosting experience. Whether for home entertaining or professional use, the BARRAID 3L Draft Beer Tower offers functionality, style, and convenience all in one.",
    "capacity": "3L",
    "sourceUrl": "https://www.barraid.com/index.php?route=product/product&product_id=207"
  },
  {
    "id": 208,
    "legacyProductId": 208,
    "slug": "barraid-3l-draft-beer-tower-with-sparkling-light-ice-tube-beverage-dispenser-for-beer-liqu-208",
    "name": "BARRAID 3L Draft Beer Tower with Sparkling Light Ice Tube – Beverage Dispenser for Beer, Liquor, and Drinks – 3000ml Capacity, YELLOW",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/208.png",
    "code": "BT-S9",
    "availability": "In Stock",
    "description": "The BARRAID 3L Draft Beer Tower with Sparkling Light Ice Tube brings a unique and stylish touch to any gathering. With a generous 3L (3000ml) capacity, this beverage dispenser is designed to keep your favorite drinks cool and fresh without diluting them. Its built-in ice tube includes sparkling lights, adding a fun, ambient glow that enhances the atmosphere. Constructed from durable, BPA-free materials, the tower boasts a sleek green design that fits perfectly in both casual and upscale settings. The easy-to-use tap ensures smooth, controlled pouring, reducing spills and making it a great choice for parties, game nights, and other social events. Ideal for dispensing beer, cocktails, soda, juice, and other cold drinks, this versatile drink tower is perfect for anyone looking to elevate their hosting experience. Whether for home entertaining or professional use, the BARRAID 3L Draft Beer Tower offers functionality, style, and convenience all in one.",
    "capacity": "3L",
    "sourceUrl": "https://www.barraid.com/index.php?route=product/product&product_id=208"
  },
  {
    "id": 209,
    "legacyProductId": 209,
    "slug": "barraid-tripod-beer-liquor-tower-dispenser-decanter-3000-ml-3-l-capacity-for-party-home-ba-209",
    "name": "BARRAID Tripod Beer/Liquor Tower/Dispenser/Decanter, 3000 ml/3 L Capacity, for Party/Home/Bars/Pubs",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/209.png",
    "code": "BT-S10",
    "availability": "In Stock",
    "description": "The BARRAID Tripod Beer/Liquor Tower Dispenser is a must-have for parties, gatherings, and social events, designed to enhance any drinking experience. With an impressive 3-liter (3000 ml) capacity, this dispenser holds enough liquid to keep the fun going without frequent refills, making it ideal for sharing with family and friends. Whether you’re pouring beer, cocktails, juice, or any other beverage, this dispenser is a versatile addition to your barware collection. This dispenser is crafted with a sleek, modern tripod base that offers unmatched stability and style, keeping the tower securely in place even in lively party settings. The dispenser’s tap is designed for easy, smooth pouring, making it simple for guests to help themselves while minimizing spills and mess. Made from transparent, durable material, the BARRAID dispenser features volume indicators so you can easily monitor remaining beverage levels at a glance. Perfect for casual gatherings, sports events, BBQs, and celebrations, this beverage tower is versatile enough to fit in at home or at any professional bar setting. Its functional design and large capacity make it a great choice for entertaining, allowing you to enjo",
    "capacity": "3000 ml",
    "sourceUrl": "https://www.barraid.com/index.php?route=product/product&product_id=209"
  },
  {
    "id": 210,
    "legacyProductId": 210,
    "slug": "barraid-custom-tall-table-beer-liquor-dispenser-decanter-for-beer-whisky-wine-capacity-for-210",
    "name": "BARRAID Custom Tall Table Beer/Liquor Dispenser/Decanter for Beer/Whisky/Wine Capacity for Party/Home/Bars/Pubs with Multi Sparking LED Light ice Tube(3000 ml/3 L) (Black)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/210.png",
    "code": "BT-NT01",
    "availability": "In Stock",
    "description": "Add a touch of style and convenience to your drinking experience with the BARRAID Custom Tall Table Beer/Liquor Dispenser. With a generous 3L (3000 ml) capacity, this dispenser is designed to keep your guests’ favorite beverages flowing at any event. Whether you're hosting a party, running a bar, or adding flair to your home gatherings, this versatile dispenser brings a professional touch to any setting. Equipped with a unique multi-color LED lighting feature, the BARRAID dispenser enhances any atmosphere by illuminating the drink and creating an eye-catching centerpiece. Perfect for parties, pubs, or game nights, the lighting adds an extra level of excitement and is sure to impress guests. To ensure drinks stay cool without losing their flavor, the dispenser includes an integrated ice tube. Simply fill it with ice, and your beverages remain chilled without being diluted. The BPA-free construction ensures safe drinking, and the durable plastic is both shatter-resistant and lightweight, making it easy to carry and use in various environments. The user-friendly tap and handle make serving drinks effortless, allowing everyone to pour with ease and enjoy spill-free servings. Compatible",
    "capacity": "3000 ml",
    "sourceUrl": "https://www.barraid.com/index.php?route=product/product&product_id=210"
  },
  {
    "id": 212,
    "legacyProductId": 212,
    "slug": "barraid-custom-tall-table-beer-liquor-dispenser-decanter-for-beer-whisky-wine-capacity-for-212",
    "name": "BARRAID Custom Tall Table Beer/Liquor Dispenser/Decanter for Beer/Whisky/Wine Capacity for Party/Home/Bars/Pubs with Multi Sparking LED Light ice Tube(3000 ml/3 L) (PINK)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/212.png",
    "code": "BT-NT01",
    "availability": "In Stock",
    "description": "Add a touch of style and convenience to your drinking experience with the BARRAID Custom Tall Table Beer/Liquor Dispenser. With a generous 3L (3000 ml) capacity, this dispenser is designed to keep your guests’ favorite beverages flowing at any event. Whether you're hosting a party, running a bar, or adding flair to your home gatherings, this versatile dispenser brings a professional touch to any setting. Equipped with a unique multi-color LED lighting feature, the BARRAID dispenser enhances any atmosphere by illuminating the drink and creating an eye-catching centerpiece. Perfect for parties, pubs, or game nights, the lighting adds an extra level of excitement and is sure to impress guests. To ensure drinks stay cool without losing their flavor, the dispenser includes an integrated ice tube. Simply fill it with ice, and your beverages remain chilled without being diluted. The BPA-free construction ensures safe drinking, and the durable plastic is both shatter-resistant and lightweight, making it easy to carry and use in various environments. The user-friendly tap and handle make serving drinks effortless, allowing everyone to pour with ease and enjoy spill-free servings. Compatible",
    "capacity": "3000 ml",
    "sourceUrl": "https://www.barraid.com/index.php?route=product/product&product_id=212"
  },
  {
    "id": 218,
    "legacyProductId": 218,
    "slug": "barraid-elite-tower-dispenser-decanter-for-beer-whisky-wine-capacity-for-party-home-bars-p-218",
    "name": "BARRAID Elite Tower/Dispenser/Decanter for Beer/Whisky/Wine Capacity for Party/Home/Bars/Pubs (3000 ml/3 L) (WOODEN PATTERN)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/218.png",
    "code": "BT-S23",
    "availability": "In Stock",
    "description": "The BARRAID Elite Tower/Dispenser/Decanter is a must-have for anyone looking to elevate their beverage service experience. With its 3000 ml (3 L) capacity, this dispenser is perfect for entertaining large groups without the hassle of constant refilling. Whether you're serving beer, whisky, wine, or creative cocktails, this tower is designed to make every pour smooth and convenient. Crafted from premium, BPA-free materials, the BARRAID Elite Tower guarantees durability and safety. Its sturdy construction ensures it can withstand frequent use, making it suitable for parties, casual home use, or even professional bar and pub settings. The vibrant blue finish adds a pop of color, blending seamlessly with various event themes or modern interiors. Functionality meets style with the easy-to-use tap, designed for smooth and precise pouring. Guests can serve themselves effortlessly, while the stable base keeps the dispenser secure. Cleaning and maintenance are equally simple, thanks to its detachable components. Whether you're hosting a backyard barbecue, a festive celebration, or running a busy bar, the BARRAID Elite Tower brings sophistication and practicality to the table. Its eye-catchi",
    "capacity": "3000 ml",
    "sourceUrl": "https://www.barraid.com/index.php?route=product/product&product_id=218"
  },
  {
    "id": 226,
    "legacyProductId": 226,
    "slug": "barraid-beer-tower-beverage-dispenser-3-litre-tabletop-draft-drink-dispenser-yellow-226",
    "name": "BARRAID Beer Tower Beverage Dispenser, 3 Litre, Tabletop Draft Drink Dispenser (Yellow)",
    "category": "Beer Towers",
    "price": 3599,
    "oldPrice": 4999,
    "image": "/barraid/products/226.png",
    "code": "SD198",
    "availability": "2-3 Days",
    "description": "Elevate your parties and gatherings with this sleek 3-litre beverage dispenser, featuring a striking green base and transparent cylinder design. The tall, slender tower configuration adds a modern touch to any setting while maximising your counter or table space. The durable construction includes a precise dispensing tap that provides smooth, controlled pouring without drips or spills. Perfect for serving cold drinks, juices, or cocktails, this dispenser keeps beverages readily accessible for your guests. The wide-mouth top allows for easy filling and cleaning, while the clear container lets you monitor beverage levels at a glance. The stable base ensures secure placement, making it ideal for both indoor and outdoor entertaining. Whether hosting a casual get-together or a formal event, this practical dispenser combines style with functionality to keep your beverages flowing and your guests refreshed.",
    "capacity": "3 Litre",
    "sourceUrl": "https://www.barraid.com/index.php?route=product/product&product_id=226"
  }
];
export const legacySlugToId:Record<string,number>={"tripod-beer-liquor-tower-3l":209,"double-gas-pump-liquor-dispenser-900ml":104,"green-beer-boot-glass":53,"sparkling-light-draft-beer-tower-3l":208,"elite-tower-3l-wooden-pattern":218,"dual-tap-beer-tower-3l-silver":231,"tabletop-draft-drink-dispenser-3l":226};
export const productBySlug=(slug:string)=>products.find(p=>p.slug===slug)||products.find(p=>p.id===legacySlugToId[slug]);
export const categories=[...new Set(products.map(p=>p.category))];
