export type BarRaidProduct={id:number;slug:string;name:string;category:string;price:number;oldPrice?:number;image:string;code:string;availability:string;description:string;capacity:string};
export const products:BarRaidProduct[]=[
{id:1,slug:"tripod-beer-liquor-tower-3l",name:"Tripod Beer / Liquor Tower 3L",category:"Beer Towers",price:3599,oldPrice:4999,image:"/barraid/official-209.jpg",code:"BT-S10",availability:"In Stock",description:"3 litre (3000 ml) tripod beverage tower for parties, home bars and hospitality service.",capacity:"3 L"},
{id:2,slug:"double-gas-pump-liquor-dispenser-900ml",name:"Double Gas Pump Liquor Dispenser 900 ML",category:"Liquor Dispensers",price:1999,oldPrice:2799,image:"/barraid/gas-pump.jpg",code:"BarRaid catalogue",availability:"Confirm at order",description:"Twin-pour 900 ml countertop liquor dispenser inspired by classic fuel pumps.",capacity:"900 ML"},
{id:3,slug:"green-beer-boot-glass",name:"Green Beer Boot Glass",category:"Novelty Glassware",price:599,oldPrice:1399,image:"/barraid/beer-boot.jpg",code:"BarRaid catalogue",availability:"Confirm at order",description:"Statement boot-shaped beer glass for home bars, gifting, parties and venue presentation.",capacity:"See catalogue"},
{id:4,slug:"sparkling-light-draft-beer-tower-3l",name:"3L Sparkling Light Draft Beer Tower",category:"Beer Towers",price:3599,oldPrice:4999,image:"/barraid/official-208.jpg",code:"BT-S9",availability:"In Stock",description:"3 litre draft beverage tower with an illuminated ice tube for cold-drink service and entertaining.",capacity:"3 L"},
{id:5,slug:"elite-tower-3l-wooden-pattern",name:"Elite Tower 3L - Wooden Pattern",category:"Beer Towers",price:3599,oldPrice:4999,image:"/barraid/official-218.jpg",code:"BT-S23",availability:"In Stock",description:"3 litre Elite beverage tower for beer, whisky, wine and cold-drink service.",capacity:"3 L"},
{id:6,slug:"dual-tap-beer-tower-3l-silver",name:"Dual-Tap Beer Tower 3L - Silver",category:"Beer Towers",price:3599,oldPrice:4999,image:"/barraid/official-231.jpg",code:"SD398",availability:"Out Of Stock",description:"3 litre tabletop beverage tower with dual taps and a clear vessel.",capacity:"3 L"},
{id:7,slug:"tabletop-draft-drink-dispenser-3l",name:"Tabletop Draft Drink Dispenser 3L",category:"Beer Towers",price:3599,oldPrice:4999,image:"/barraid/official-226.jpg",code:"SD198",availability:"2-3 Days",description:"3 litre tabletop beverage dispenser with a clear tower and controlled dispensing tap.",capacity:"3 L"}
];
export const productBySlug=(slug:string)=>products.find(p=>p.slug===slug);