"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type Doctor = { name:string; dept:string; exp:string; icon:string; fee:number; rating:number; next:string; slots:string[]; modes:string[] };
const doctors:Doctor[] = [
  { name:"Dr. Meera Shah", dept:"Dermatology", exp:"12 yrs", icon:"👩‍⚕️", fee:900, rating:4.9, next:"10:30 AM", slots:["10:30","12:00","16:30"], modes:["Clinic","Video"] },
  { name:"Dr. Arjun Rao", dept:"Cardiology", exp:"15 yrs", icon:"👨‍⚕️", fee:1200, rating:4.8, next:"09:30 AM", slots:["09:30","14:00","17:00"], modes:["Clinic","Video"] },
  { name:"Dr. Sana Khan", dept:"Pediatrics", exp:"10 yrs", icon:"🩺", fee:750, rating:4.9, next:"11:00 AM", slots:["11:00","13:30","18:00"], modes:["Clinic"] },
  { name:"Dr. Rohan Iyer", dept:"Orthopedics", exp:"14 yrs", icon:"🦴", fee:1000, rating:4.7, next:"12:30 PM", slots:["12:30","15:30","19:00"], modes:["Clinic","Video"] },
];
const dates=["Today","Tomorrow","Mon 10","Tue 11"];

export default function ClinicDemoClient() {
  const [specialty,setSpecialty]=useState("All");
  const [doctor,setDoctor]=useState(0);
  const [slot,setSlot]=useState("");
  const [date,setDate]=useState("Today");
  const [mode,setMode]=useState("Clinic");
  const [patient,setPatient]=useState("");
  const [phone,setPhone]=useState("");
  const [reason,setReason]=useState("");
  const [confirmed,setConfirmed]=useState(false);
  const [portal,setPortal]=useState(false);

  const visible = useMemo(()=> specialty==="All" ? doctors : doctors.filter(d=>d.dept===specialty),[specialty]);
  const selected = doctors[doctor];

  function chooseDoctor(index:number){ setDoctor(index); setSlot(""); setConfirmed(false); if(!doctors[index].modes.includes(mode)) setMode(doctors[index].modes[0]); }
  const canBook = Boolean(slot && patient.trim() && phone.trim());

  return <main className="min-h-screen bg-gradient-to-b from-[#eefcfb] via-[#f8ffff] to-[#eaf4ff] text-[#113b3b]" style={{fontFamily: "Trebuchet MS, Segoe UI, Arial, sans-serif"}}>
    <header className="sticky top-0 z-40 border-b border-teal-900/10 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div className="flex items-center gap-6"><Link href="/#work" className="text-sm font-bold text-teal-900/50">← Portfolio</Link><div className="text-xl font-black">Medi<span className="text-teal-500">Nova</span></div></div><div className="hidden gap-7 text-sm font-semibold md:flex"><a href="#doctors">Doctors</a><span>Diagnostics</span><span>Health plans</span></div><button onClick={()=>setPortal(true)} className="rounded-full bg-teal-600 px-5 py-2.5 text-sm font-black text-white">Patient portal</button></div></header>

    <section className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-16 lg:grid-cols-2"><div><div className="inline-flex rounded-full bg-cyan-100 px-4 py-2 text-xs font-black uppercase tracking-[.2em] text-cyan-800">Production-style healthcare demo</div><h1 className="mt-6 text-5xl font-black leading-tight sm:text-6xl">Care that starts <span className="text-teal-500">before</span> the waiting room.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-teal-950/60">Specialist discovery, filters, in-clinic/video consultations, patient intake, fee summary, appointment confirmation and a lightweight patient portal.</p><div className="mt-8 grid grid-cols-3 gap-3">{[["24/7","Booking"],["4.9/5","Patient rating"],["15 min","Avg. slot"]].map(([a,b])=><div key={b} className="rounded-[2rem] bg-white p-4 shadow-[0_14px_40px_rgba(13,148,136,0.08)]"><div className="text-2xl font-black text-teal-600">{a}</div><div className="mt-1 text-xs font-semibold text-teal-950/50">{b}</div></div>)}</div></div><div className="rounded-[2rem] bg-gradient-to-br from-teal-600 to-cyan-500 p-7 text-white shadow-2xl"><div className="flex items-start justify-between"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-white/70">Smart care desk</div><div className="mt-2 text-3xl font-black">Find the right doctor</div></div><div className="text-5xl">🏥</div></div><div className="mt-7 grid gap-3 sm:grid-cols-2"><div className="rounded-[2rem] bg-white/15 p-5"><div className="text-sm text-white/60">Next available</div><div className="mt-2 text-2xl font-black">09:30 AM</div></div><div className="rounded-[2rem] bg-white p-5 text-teal-900"><div className="text-sm text-teal-900/50">Open specialists</div><div className="mt-2 text-2xl font-black">12 doctors</div></div></div><div className="mt-3 rounded-[2rem] bg-black/15 p-4 text-sm font-bold text-white/80">✓ WhatsApp reminders &nbsp; ✓ Digital prescriptions &nbsp; ✓ Video consult ready</div></div></section>

    <section id="doctors" className="mx-auto max-w-7xl px-5 pb-20"><div><div className="text-xs font-black uppercase tracking-[.2em] text-teal-500">Interactive booking</div><h2 className="mt-2 text-4xl font-black">Book a specialist</h2></div>
      <div className="mt-6 flex flex-wrap gap-2">{["All","Dermatology","Cardiology","Pediatrics","Orthopedics"].map(s=><button key={s} onClick={()=>setSpecialty(s)} className={`rounded-full px-4 py-2 text-sm font-black ${specialty===s?"bg-teal-700 text-white":"border border-teal-900/10 bg-white text-teal-800"}`}>{s}</button>)}</div>
      <div className="mt-6 grid gap-5 lg:grid-cols-[.78fr_1.22fr]"><div className="space-y-3">{visible.map((d)=>{const i=doctors.indexOf(d); return <button key={d.name} onClick={()=>chooseDoctor(i)} className={`w-full rounded-[2rem] border p-5 text-left transition ${doctor===i?"border-teal-500 bg-teal-600 text-white shadow-lg":"border-teal-900/10 bg-white hover:border-teal-300"}`}><div className="flex items-center gap-4"><div className="text-4xl">{d.icon}</div><div className="min-w-0 flex-1"><div className="font-black">{d.name}</div><div className={`text-sm ${doctor===i?"text-white/70":"text-teal-900/50"}`}>{d.dept} • {d.exp}</div><div className={`mt-2 text-xs font-bold ${doctor===i?"text-white/75":"text-teal-700"}`}>★ {d.rating} • Next {d.next} • ₹{d.fee}</div></div></div></button>})}</div>
        <div className="rounded-[2rem] border border-teal-900/10 bg-white p-7 shadow-[0_14px_40px_rgba(13,148,136,0.08)]"><div className="flex items-center justify-between"><div><div className="text-sm text-teal-900/50">Selected doctor</div><div className="mt-1 text-2xl font-black">{selected.name}</div><div className="mt-1 text-sm font-bold text-teal-700">{selected.dept} • ★ {selected.rating}</div></div><div className="rounded-[2rem] bg-teal-50 p-4 text-4xl">{selected.icon}</div></div>
          <div className="mt-7"><div className="text-sm font-black uppercase tracking-wider text-teal-700">Consultation type</div><div className="mt-3 flex gap-2">{selected.modes.map(m=><button key={m} onClick={()=>setMode(m)} className={`rounded-[1.4rem] px-5 py-3 font-black ${mode===m?"bg-teal-700 text-white":"bg-teal-50 text-teal-800"}`}>{m==="Video"?"🎥 ":"🏥 "}{m}</button>)}</div></div>
          <div className="mt-6"><div className="text-sm font-black uppercase tracking-wider text-teal-700">Choose date</div><div className="mt-3 flex flex-wrap gap-2">{dates.map(d=><button key={d} onClick={()=>{setDate(d);setSlot("");setConfirmed(false)}} className={`rounded-[1.4rem] px-4 py-3 text-sm font-black ${date===d?"bg-cyan-500 text-white":"border border-teal-900/10 bg-white"}`}>{d}</button>)}</div></div>
          <div className="mt-6"><div className="text-sm font-black uppercase tracking-wider text-teal-700">Available slots</div><div className="mt-3 flex flex-wrap gap-3">{selected.slots.map(s=><button key={s} onClick={()=>{setSlot(s);setConfirmed(false)}} className={`rounded-[1.4rem] px-5 py-3 font-bold ${slot===s?"bg-teal-600 text-white":"bg-teal-50 text-teal-800"}`}>{s}</button>)}</div></div>
          <div className="mt-7 grid gap-3 sm:grid-cols-2"><input value={patient} onChange={e=>setPatient(e.target.value)} className="rounded-[1.4rem] border border-teal-900/10 bg-[#f8ffff] px-4 py-3 outline-none" placeholder="Patient name"/><input value={phone} onChange={e=>setPhone(e.target.value)} className="rounded-[1.4rem] border border-teal-900/10 bg-[#f8ffff] px-4 py-3 outline-none" placeholder="Phone / WhatsApp"/><textarea value={reason} onChange={e=>setReason(e.target.value)} className="min-h-24 rounded-[1.4rem] border border-teal-900/10 bg-[#f8ffff] px-4 py-3 outline-none sm:col-span-2" placeholder="Reason for visit / symptoms (optional)"/></div>
          <div className="mt-5 rounded-[2rem] bg-teal-50 p-5"><div className="flex justify-between text-sm"><span className="text-teal-900/55">Doctor fee</span><span className="font-black">₹{selected.fee}</span></div><div className="mt-2 flex justify-between text-sm"><span className="text-teal-900/55">Booking fee</span><span className="font-black">₹0</span></div><div className="mt-3 flex justify-between border-t border-teal-900/10 pt-3 text-lg font-black"><span>Total</span><span>₹{selected.fee}</span></div></div>
          <button disabled={!canBook} onClick={()=>setConfirmed(true)} className="mt-4 w-full rounded-[1.4rem] bg-cyan-500 py-4 font-black text-white disabled:opacity-40">Confirm & pay at clinic →</button>{!canBook&&<div className="mt-2 text-center text-xs font-bold text-teal-900/35">Select a slot and enter patient name + phone.</div>}{confirmed && <div className="mt-4 rounded-[1.4rem] bg-emerald-50 p-5 text-emerald-800"><div className="font-black">✓ Appointment confirmed</div><div className="mt-1 text-sm">{patient} • {selected.name} • {date} at {slot} • {mode}</div><div className="mt-2 text-xs font-bold text-emerald-700/65">Reminder workflow, calendar event and patient record would be created in production.</div></div>}
        </div></div></section>

    {portal&&<div className="fixed inset-0 z-50 grid place-items-center bg-teal-950/55 p-4" onClick={()=>setPortal(false)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-3xl rounded-[2rem] bg-white p-7 shadow-2xl"><div className="flex items-start justify-between"><div><div className="text-xs font-black uppercase tracking-[.2em] text-teal-500">Patient portal demo</div><h3 className="mt-2 text-3xl font-black">Welcome back, Priya</h3></div><button onClick={()=>setPortal(false)} className="text-3xl">×</button></div><div className="mt-7 grid gap-4 md:grid-cols-3">{[["Next visit","Dermatology • Aug 12"],["Prescriptions","2 active"],["Reports","5 documents"]].map(([a,b])=><div key={a} className="rounded-[2rem] bg-teal-50 p-5"><div className="text-xs font-black uppercase tracking-wider text-teal-700/50">{a}</div><div className="mt-2 font-black">{b}</div></div>)}</div><div className="mt-5 rounded-[2rem] border border-teal-900/10 p-5"><div className="font-black">Recent care timeline</div><div className="mt-4 space-y-4">{[["Aug 02","Blood test report uploaded"],["Jul 19","Video consultation completed"],["Jun 28","Prescription renewed"]].map(([d,t])=><div key={d} className="flex gap-4"><div className="w-16 text-xs font-black text-teal-500">{d}</div><div className="text-sm font-bold text-teal-900/70">{t}</div></div>)}</div></div></div></div>}
  </main>
}
