"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
const services=[
 ["Family & Residence","Family Residence Visa","family-residence-visa"],["Family & Residence","Family Visa Cost","family-visa-cost"],["Family & Residence","Spouse Residence Visa","spouse-visa"],["Family & Residence","Children Residence Visa","children-visa"],["Family & Residence","Parents Residence Visa","parents-visa"],["Family & Residence","Family Visa Renewal","family-visa-renewal"],["Family & Residence","Newborn Visa","newborn-visa"],["Family & Residence","Domestic Worker Visa","domestic-worker-visa"],["Long-term & Employment","Golden Visa","golden-visa"],["Long-term & Employment","Golden Visa Cost","golden-visa-cost"],["Long-term & Employment","Property Investor Visa","property-investor-visa"],["Long-term & Employment","Employment Visa","employment-visa"],["Identity","Emirates ID","emirates-id"],["Identity","Emirates ID Typing","emirates-id-typing"],["Identity","Emirates ID Renewal","emirates-id-renewal"],["Identity","Lost or Damaged Emirates ID","emirates-id-replacement"],["Identity","Medical Fitness Guidance","medical-fitness"],["Identity","Visa Medical Fitness","visa-medical"],["Identity","Emirates ID Fees & Cost Guide","emirates-id-cost"],["Business & PRO","Business Setup","business-setup"],["Business & PRO","Amer Services at Home","amer-services-home"],["Business & PRO","Amer Centres Near Me","amer-centres-near-me"],["Business & PRO","Health Insurance","health-insurance"],["Business & PRO","PRO Services","pro-services"],["Business & PRO","New Employee Visa","new-employee-visa"],["Business & PRO","Employee Visa Renewal","employee-visa-renewal"],["Business & PRO","Relative Work Permit","relative-work-permit"],["Business & PRO","Golden Visa Work Permit","golden-visa-work-permit"],["Business & PRO","Part-Time & Intern Work Permit","part-time-work-permit"],["Business & PRO","Visa Cancellation","visa-cancellation"],["Business & PRO","Government Processing","government-processing"],["Business & PRO","Immigration Services","immigration-services"],["Business & PRO","Check UAE Visa Status","check-visa-status"],["Business & PRO","Business Support","business-support"],["Documents","Document Attestation","document-attestation"],["Documents","Legal Translation","legal-translation"],["Documents","Power of Attorney","power-of-attorney"],["Documents","Wills & Testament","wills-testament"],["Documents","Visa Document & Photo Specifications","document-photo-specifications"],["Government & Property","Medical & Emirates ID Centre Guidance","medical-id-centres"],["Government & Property","Amer Center Guidance","amer-center"],["Government & Property","DLD Trustee Services","dld-trustee-services"],["Government & Property","Property Revaluation Guidance","property-revaluation"],["Government & Property","ILOE Guidance","iloe"]
];
export default function ServiceDirectory(){
 const [category,setCategory]=useState("All");
 const [query,setQuery]=useState("");
 const [visibleCount,setVisibleCount]=useState(12);
 const categories=["All","Family & Residence","Long-term & Employment","Identity","Business & PRO","Documents","Government & Property"];
 const visible=useMemo(()=>services.filter(([group,title])=>(category==="All"||group===category)&&`${group} ${title}`.toLowerCase().includes(query.toLowerCase())),[category,query]);
 useEffect(()=>setVisibleCount(12),[category,query]);
 const displayed=visible.slice(0,visibleCount);
 const remaining=visible.length-displayed.length;
 return <>
  <div className="fv-directory-intro"><label htmlFor="service-search">What do you need help with?</label><input id="service-search" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Try family visa, Golden Visa, Emirates IDâ€¦"/><Link href="/demos/familyvisauae/calculators/family">Not sure which route fits? Use the quick route checker →</Link></div>
  <div className="fv-directory-filter">{categories.map(item=><button type="button" key={item} className={category===item?"is-active":""} onClick={()=>setCategory(item)}>{item}</button>)}</div>
  <p className="fv-directory-count">{visible.length} services match your selection.</p>
  <div className="service-grid">{displayed.map(([group,title,slug],index)=><article key={slug}><span>{group} · {String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>Documents, process guidance and a direct WhatsApp route for this service.</p><Link href={`/demos/familyvisauae/${slug}`}>View service →</Link></article>)}</div>
  {remaining>0&&<div className="fv-directory-more"><button type="button" onClick={()=>setVisibleCount(current=>current+12)}>Show {Math.min(remaining,12)} more services <span aria-hidden="true">â†“</span></button><p>{remaining} more services available</p></div>}
  {visible.length===0&&<div className="fv-directory-empty"><strong>No exact match yet.</strong><p>Use the route checker for a guided start, or ask us on WhatsApp with your situation.</p><Link href="/demos/familyvisauae/calculators/family">Open route checker →</Link></div>}
 </>}


