"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type Activity={time:string;text:string};
type Lead={id:number;name:string;company:string;email:string;value:number;stage:string;source:string;score:number;activities:Activity[]};
const seed:Lead[]=[
  {id:1,name:"Ava Morgan",company:"BrightLabs",email:"ava@brightlabs.io",value:120000,stage:"New",source:"Website",score:82,activities:[{time:"10:42",text:"Downloaded automation guide"},{time:"09:55",text:"Lead captured from website"}]},
  {id:2,name:"Noah Lee",company:"Craftly",email:"noah@craftly.co",value:240000,stage:"Qualified",source:"Referral",score:91,activities:[{time:"12:05",text:"Discovery call completed"},{time:"Yesterday",text:"Referral lead created"}]},
  {id:3,name:"Mia Chen",company:"Northstar",email:"mia@northstar.ai",value:360000,stage:"Proposal",source:"LinkedIn",score:96,activities:[{time:"14:20",text:"Proposal opened"},{time:"11:30",text:"Pricing deck sent"}]},
  {id:4,name:"Liam Scott",company:"Orbit Foods",email:"liam@orbitfoods.com",value:185000,stage:"New",source:"Ads",score:71,activities:[{time:"13:15",text:"Requested product demo"}]},
];
const stages=["New","Qualified","Proposal","Won"];

export default function CRMDemoClient(){
  const [leads,setLeads]=useState(seed);
  const [name,setName]=useState("");
  const [company,setCompany]=useState("");
  const [value,setValue]=useState("90000");
  const [search,setSearch]=useState("");
  const [source,setSource]=useState("All");
  const [selected,setSelected]=useState<number|null>(3);
  const [aiDraft,setAiDraft]=useState("");
  const [automation,setAutomation]=useState(true);
  const total=useMemo(()=>leads.reduce((s,l)=>s+l.value,0),[leads]);
  const weighted=useMemo(()=>Math.round(leads.reduce((s,l)=>s+l.value*({New:.2,Qualified:.5,Proposal:.75,Won:1}[l.stage as "New"|"Qualified"|"Proposal"|"Won"]||0),0)),[leads]);
  const filtered=useMemo(()=>leads.filter(l=>(source==="All"||l.source===source)&&(l.name.toLowerCase().includes(search.toLowerCase())||l.company.toLowerCase().includes(search.toLowerCase()))),[leads,search,source]);
  const selectedLead=leads.find(l=>l.id===selected)||null;

  const advance=(id:number)=>setLeads(v=>v.map(l=>{if(l.id!==id)return l;const i=stages.indexOf(l.stage);const next=stages[Math.min(i+1,stages.length-1)];return {...l,stage:next,activities:[{time:"Now",text:`Moved to ${next}`},...l.activities]}}));
  const add=()=>{if(!name.trim())return;const id=Date.now();setLeads(v=>[{id,name,company:company||"New account",email:"lead@example.com",value:Number(value)||90000,stage:"New",source:"Manual",score:68,activities:[{time:"Now",text:"Lead created manually"}]},...v]);setName("");setCompany("");setValue("90000");setSelected(id)};
  const draft=(lead:Lead)=>{setSelected(lead.id);setAiDraft(`Hi ${lead.name.split(" ")[0]}, thanks for your interest in our solution. Based on our conversation with ${lead.company}, I have outlined the next step and a short implementation path that matches your priorities. Would ${lead.stage==="Proposal"?"Tuesday at 3 PM":"tomorrow morning"} work for a 20-minute follow-up?`)};

  return <main className="min-h-screen bg-[#f1f3f7] text-slate-900" style={{fontFamily: "Segoe UI, Arial, sans-serif"}}><header className="sticky top-0 z-40 border-b bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4"><div className="flex items-center gap-6"><Link href="/#work" className="text-sm font-bold text-slate-400">← Portfolio</Link><div className="text-xl font-black text-indigo-600">PipelineOS</div></div><div className="flex items-center gap-3"><div className="hidden rounded-full bg-emerald-50 px-4 py-2 text-xs font-black text-emerald-700 sm:block">● LIVE WORKSPACE</div><button onClick={()=>setAutomation(v=>!v)} className={`rounded-full px-4 py-2 text-xs font-black ${automation?"bg-indigo-50 text-indigo-700":"bg-slate-100 text-slate-500"}`}>⚡ Automation {automation?"ON":"OFF"}</button></div></div></header>
  <div className="mx-auto max-w-[1500px] px-5 py-8"><div className="grid gap-5 lg:grid-cols-[240px_1fr]"><aside className="rounded-3xl bg-[#111827] p-5 text-white"><div className="text-xs font-black uppercase tracking-[.2em] text-white/40">Workspace</div><nav className="mt-5 space-y-2">{["▣ Dashboard","◎ Pipeline","◉ Contacts","✦ Automations","▥ Reports"].map((x,i)=><div key={x} className={`rounded-md px-4 py-3 text-sm font-bold ${i===1?"bg-indigo-500":"text-white/60"}`}>{x}</div>)}</nav><div className="mt-10 rounded-md bg-white/10 p-4"><div className="text-xs text-white/40">AI follow-ups</div><div className="mt-2 text-2xl font-black">18 queued</div><div className="mt-2 text-xs text-emerald-300">↑ 22% reply rate</div></div></aside>
  <section><div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><div className="text-xs font-black uppercase tracking-[.2em] text-indigo-500">Production-style B2B CRM demo</div><h1 className="mt-2 text-4xl font-black">Sales pipeline</h1><p className="mt-2 text-slate-500">Create, qualify, inspect and progress opportunities with AI-assisted follow-up.</p></div><div className="grid gap-2 sm:grid-cols-4"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Lead name" className="rounded-md border bg-white px-3 py-3 outline-none"/><input value={company} onChange={e=>setCompany(e.target.value)} placeholder="Company" className="rounded-md border bg-white px-3 py-3 outline-none"/><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Value" className="rounded-md border bg-white px-3 py-3 outline-none"/><button onClick={add} className="rounded-md bg-indigo-600 px-5 py-3 font-black text-white">+ Add lead</button></div></div>
  <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Pipeline value",`₹${(total/100000).toFixed(1)}L`],["Weighted forecast",`₹${(weighted/100000).toFixed(1)}L`],["Open opportunities",String(leads.filter(l=>l.stage!=="Won").length)],["Won revenue",`₹${(leads.filter(l=>l.stage==="Won").reduce((s,l)=>s+l.value,0)/100000).toFixed(1)}L`]].map(([a,b])=><div key={a} className="rounded-md border bg-white p-5"><div className="text-sm text-slate-400">{a}</div><div className="mt-2 text-3xl font-black">{b}</div></div>)}</div>
  <div className="mt-5 flex flex-col gap-3 rounded-md border bg-white p-3 sm:flex-row"><input value={search} onChange={e=>setSearch(e.target.value)} className="min-w-0 flex-1 rounded-md bg-slate-50 px-4 py-3 text-sm outline-none" placeholder="Search lead or company…"/><div className="flex flex-wrap gap-2">{["All","Website","Referral","LinkedIn","Ads","Manual"].map(x=><button key={x} onClick={()=>setSource(x)} className={`rounded-md px-3 py-2 text-xs font-black ${source===x?"bg-indigo-600 text-white":"bg-slate-50 text-slate-500"}`}>{x}</button>)}</div></div>
  <div className="mt-6 grid gap-4 xl:grid-cols-4">{stages.map(stage=><div key={stage} className="min-h-[300px] rounded-md bg-slate-100 p-3"><div className="flex items-center justify-between px-2 py-2"><div className="font-black">{stage}</div><span className="rounded-full bg-white px-2 py-1 text-xs font-bold text-slate-500">{filtered.filter(l=>l.stage===stage).length}</span></div><div className="space-y-3">{filtered.filter(l=>l.stage===stage).map(l=><article key={l.id} onClick={()=>setSelected(l.id)} className={`cursor-pointer rounded-md border bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${selected===l.id?"ring-2 ring-indigo-400":""}`}><div className="flex items-start justify-between"><div><div className="font-black">{l.name}</div><div className="mt-1 text-sm text-slate-400">{l.company}</div></div><span className={`rounded-full px-2 py-1 text-[10px] font-black ${l.score>=90?"bg-emerald-50 text-emerald-700":l.score>=80?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-500"}`}>{l.score} score</span></div><div className="mt-3 flex items-center justify-between"><span className="text-xs font-bold text-slate-400">{l.source}</span><span className="font-black text-indigo-600">₹{(l.value/1000).toFixed(0)}K</span></div><div className="mt-4 grid grid-cols-2 gap-2">{stage!=="Won"&&<button onClick={(e)=>{e.stopPropagation();advance(l.id)}} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-black text-white">Advance →</button>}<button onClick={(e)=>{e.stopPropagation();draft(l)}} className="rounded-lg bg-indigo-50 px-3 py-2 text-xs font-black text-indigo-700">✦ AI follow-up</button></div></article>)}</div></div>)}</div>
  <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_360px]"><div className="rounded-3xl bg-gradient-to-r from-indigo-600 to-violet-600 p-6 text-white"><div className="grid gap-5 md:grid-cols-3"><div><div className="text-sm text-white/60">Automation health</div><div className="mt-2 text-3xl font-black">{automation?"98.7%":"Paused"}</div></div><div><div className="text-sm text-white/60">Response SLA</div><div className="mt-2 text-3xl font-black">4m 12s</div></div><div><div className="text-sm text-white/60">Next action</div><div className="mt-2 font-black">{automation?"AI drafts follow-up for 6 leads":"Resume workflows to continue"}</div></div></div></div>
  {selectedLead&&<div className="rounded-3xl border bg-white p-5"><div className="flex items-start justify-between"><div><div className="text-xs font-black uppercase tracking-wider text-indigo-500">Selected opportunity</div><div className="mt-1 text-xl font-black">{selectedLead.name}</div><div className="text-sm text-slate-400">{selectedLead.company}</div></div><button onClick={()=>setSelected(null)} className="text-xl text-slate-300">×</button></div><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><div className="rounded-md bg-slate-50 p-3"><div className="text-xs text-slate-400">Deal</div><div className="font-black">₹{selectedLead.value.toLocaleString("en-IN")}</div></div><div className="rounded-md bg-slate-50 p-3"><div className="text-xs text-slate-400">Score</div><div className="font-black">{selectedLead.score}/100</div></div></div><div className="mt-4 text-xs font-black uppercase tracking-wider text-slate-400">Activity</div><div className="mt-3 space-y-3">{selectedLead.activities.slice(0,3).map((a,i)=><div key={i} className="flex gap-3 text-sm"><div className="w-16 text-xs font-bold text-slate-400">{a.time}</div><div className="font-semibold text-slate-600">{a.text}</div></div>)}</div><button onClick={()=>draft(selectedLead)} className="mt-5 w-full rounded-md bg-indigo-600 py-3 text-sm font-black text-white">✦ Generate follow-up</button></div>}</div>
  </section></div></div>

  {aiDraft&&selectedLead&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4" onClick={()=>setAiDraft("")}><div onClick={e=>e.stopPropagation()} className="w-full max-w-xl rounded-md bg-white p-7 shadow-2xl"><div className="flex justify-between"><div><div className="text-xs font-black uppercase tracking-[.2em] text-indigo-500">AI sales assistant</div><h3 className="mt-2 text-2xl font-black">Follow-up for {selectedLead.name}</h3></div><button onClick={()=>setAiDraft("")} className="text-3xl">×</button></div><textarea value={aiDraft} onChange={e=>setAiDraft(e.target.value)} className="mt-6 min-h-48 w-full rounded-md border bg-slate-50 p-4 leading-7 outline-none"/><div className="mt-4 flex gap-3"><button onClick={()=>{setLeads(v=>v.map(l=>l.id===selectedLead.id?{...l,activities:[{time:"Now",text:"AI follow-up approved and queued"},...l.activities]}:l));setAiDraft("")}} className="flex-1 rounded-md bg-indigo-600 py-3 font-black text-white">Approve & queue →</button><button className="rounded-md border px-5 font-black">Save draft</button></div><div className="mt-3 text-xs font-bold text-slate-400">Demo action: no real email is sent.</div></div></div>}
  </main>}
