"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import "../familyvisa.css";
import "./admin.css";

type Content={brand:string;phone:string;email:string;hours:string;address:string;reviewed:string;heroTitle:string;heroText:string;feesNote:string;faqNote:string};
const defaults:Content={brand:"FamilyVisaUAE",phone:"800 DOCS (3627)",email:"info@familyvisa.ae",hours:"Contact the team for current office hours",address:"709 Business Village B Block, Next to Clock Tower, Port Saeed, Deira, Dubai, UAE",reviewed:"01 September 2026",heroTitle:"A clearer way to bring your family to the UAE.",heroText:"Private consultancy support for family residence, employment, Emirates ID, PRO and document services.",feesNote:"Government charges are set by the relevant authority. Professional service fees are disclosed separately before confirmation.",faqNote:"Requirements, fees and timelines vary by route and official authority."};
export default function AdminClient(){
 const [content,setContent]=useState<Content>(defaults); const [saved,setSaved]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem("fv-cms-content");if(raw)setContent({...defaults,...JSON.parse(raw)});}catch{}},[]);
 const change=(key:keyof Content,value:string)=>{setContent(v=>({...v,[key]:value}));setSaved(false)};
 const save=()=>{localStorage.setItem("fv-cms-content",JSON.stringify(content));setSaved(true)};
 const reset=()=>{setContent(defaults);localStorage.removeItem("fv-cms-content");setSaved(false)};
 return <main className="fv-admin"><header><div><span className="fv-admin-mark">FV</span><div><b>FamilyVisaUAE</b><small>Content workspace</small></div></div><Link href="/demos/familyvisauae">View website â†—</Link></header><section className="fv-admin-shell"><aside><p>CONTENT</p><a href="#brand">Brand & contact</a><a href="#homepage">Homepage</a><a href="#fees">Fees & compliance</a><a href="#faq">FAQ guidance</a><a href="#services">Service content</a><span>Demo CMS workspace</span></aside><div className="fv-admin-main"><div className="fv-admin-title"><div><p>ADMIN / CONTENT</p><h1>Edit operational website content.</h1><span>Change common headings, contact details and compliance guidance without touching page code.</span></div><div className="fv-admin-actions"><button type="button" onClick={reset}>Reset</button><button type="button" className="save" onClick={save}>{saved?"Saved ✓":"Save changes"}</button></div></div>
 <section id="brand" className="fv-admin-card"><div><small>01</small><h2>Brand & contact</h2><p>Details used by the consultancy team.</p></div><div className="fields"><label>Brand name<input value={content.brand} onChange={e=>change("brand",e.target.value)}/></label><label>Phone / WhatsApp<input value={content.phone} onChange={e=>change("phone",e.target.value)}/></label><label>Email<input value={content.email} onChange={e=>change("email",e.target.value)}/></label><label>Office hours<input value={content.hours} onChange={e=>change("hours",e.target.value)}/></label><label className="wide">Dubai address<textarea value={content.address} onChange={e=>change("address",e.target.value)}/></label></div></section>
 <section id="homepage" className="fv-admin-card"><div><small>02</small><h2>Homepage message</h2><p>Keep the opening message clear and customer-friendly.</p></div><div className="fields"><label className="wide">Hero heading<input value={content.heroTitle} onChange={e=>change("heroTitle",e.target.value)}/></label><label className="wide">Hero supporting text<textarea value={content.heroText} onChange={e=>change("heroText",e.target.value)}/></label></div></section>
 <section id="fees" className="fv-admin-card"><div><small>03</small><h2>Fees & compliance</h2><p>Operational guidance that may need periodic review.</p></div><div className="fields"><label>Content last reviewed<input value={content.reviewed} onChange={e=>change("reviewed",e.target.value)}/></label><label className="wide">Fee guidance<textarea value={content.feesNote} onChange={e=>change("feesNote",e.target.value)}/></label></div></section>
 <section id="faq" className="fv-admin-card"><div><small>04</small><h2>FAQ guidance</h2><p>Shared caution displayed with customer guidance.</p></div><div className="fields"><label className="wide">General guidance<textarea value={content.faqNote} onChange={e=>change("faqNote",e.target.value)}/></label></div></section>
 <section id="services" className="fv-admin-card"><div><small>05</small><h2>Service content</h2><p>High-frequency service pages ready for editorial review.</p></div><div className="fv-admin-services">{["Family Residence Visa","Spouse Residence Visa","Children Residence Visa","Parents Residence Visa","Employment Visa","Golden Visa","Property Investor Visa","Business Setup","PRO Services","Emirates ID","Document Attestation","Legal Translation"].map((item,index)=><div key={item}><span>{String(index+1).padStart(2,"0")}</span><b>{item}</b><small>Heading · description · documents · process</small></div>)}</div></section><div className="fv-admin-note"><b>CMS foundation ready</b><span>This demo stores edits in this browser. Production can connect the same content model to authenticated database storage so authorised staff changes publish across devices.</span></div></div></section></main>
}

