"use client";
import { useMemo, useState } from "react";
import Link from "next/link";

const homes = [
 {name:"Skyline Residence",city:"Dubai",type:"Apartment",price:18500000,beds:2,icon:"🏙️"},
 {name:"Palm Court Villa",city:"Goa",type:"Villa",price:32000000,beds:4,icon:"🏡"},
 {name:"Park Avenue Loft",city:"Bengaluru",type:"Apartment",price:14500000,beds:3,icon:"🌆"},
 {name:"Azure Beach House",city:"Goa",type:"Villa",price:41000000,beds:4,icon:"🌴"},
];
export default function RealEstateDemoClient(){
 const [city,setCity]=useState("All"); const [principal,setPrincipal]=useState(12000000); const [years,setYears]=useState(20); const filtered=useMemo(()=>city==="All"?homes:homes.filter(h=>h.city===city),[city]);
 const rate=.085/12,n=years*12; const emi=Math.round(principal*rate*Math.pow(1+rate,n)/(Math.pow(1+rate,n)-1));
 return <main className="min-h-screen bg-[#0b0d0f] text-[#f5f0e8]" style={{fontFamily: "Baskerville, Georgia, Times New Roman, serif"}}><header className="border-b border-[#c9a35e]/20"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><div className="flex items-center gap-6"><Link href="/#work" className="text-sm font-bold text-white/40">← Portfolio</Link><div className="font-serif text-2xl tracking-[.2em]">AURELIA</div></div><nav className="hidden gap-8 text-sm text-white/60 md:flex"><span>Properties</span><span>Advisory</span><span>Neighborhoods</span></nav><button className="border border-[#c9a35e] px-5 py-2.5 text-xs font-black uppercase tracking-wider text-[#e8c986]">Private viewing</button></div></header>
 <section className="relative overflow-hidden border-b border-white/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_30%,rgba(201,163,94,.18),transparent_35%)]"/><div className="relative mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[1.05fr_.95fr]"><div><div className="text-xs font-black uppercase tracking-[.35em] text-[#c9a35e]">Luxury real estate portal</div><h1 className="mt-6 font-serif text-6xl leading-[1.03] sm:text-7xl">Find a home worthy of your <i className="text-[#e8c986]">next chapter.</i></h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/55">Premium listing experience with property search, lead qualification, viewing requests and finance tools.</p><div className="mt-8 flex flex-wrap gap-2">{["All","Goa","Bengaluru","Dubai"].map(c=><button key={c} onClick={()=>setCity(c)} className={`rounded-full px-5 py-3 text-sm font-bold ${city===c?"bg-[#c9a35e] text-black":"border border-white/15 text-white/60"}`}>{c}</button>)}</div></div><div className="grid min-h-[460px] place-items-end rounded-t-[10rem] rounded-b-[2rem] border border-[#c9a35e]/20 bg-gradient-to-b from-[#384451] to-[#111518] p-7 shadow-2xl"><div className="w-full rounded-none border border-white/10 bg-black/50 p-5 backdrop-blur"><div className="text-xs uppercase tracking-[.25em] text-[#e8c986]">Featured collection</div><div className="mt-2 flex items-end justify-between"><div><div className="font-serif text-3xl">Waterfront Edition</div><div className="mt-1 text-white/50">Curated residences • Goa</div></div><div className="text-6xl">🏛️</div></div></div></div></div></section>
 <section className="mx-auto max-w-7xl px-5 py-16"><div className="flex items-end justify-between"><div><div className="text-xs font-black uppercase tracking-[.3em] text-[#c9a35e]">Available now</div><h2 className="mt-2 font-serif text-4xl">Curated properties</h2></div><div className="text-sm text-white/40">{filtered.length} matching homes</div></div><div className="mt-8 grid gap-5 md:grid-cols-2">{filtered.map(h=><article key={h.name} className="group overflow-hidden rounded-none border border-white/10 bg-[#121619]"><div className="grid h-52 place-items-center bg-gradient-to-br from-[#283039] to-[#1b2024] text-7xl">{h.icon}</div><div className="p-6"><div className="text-xs uppercase tracking-widest text-[#c9a35e]">{h.city} • {h.type}</div><div className="mt-2 flex items-start justify-between gap-4"><div><h3 className="font-serif text-2xl">{h.name}</h3><div className="mt-2 text-white/45">{h.beds} bedrooms • concierge viewing</div></div><div className="font-black text-[#e8c986]">₹{(h.price/10000000).toFixed(2)} Cr</div></div><button className="mt-5 w-full border border-white/15 py-3 text-sm font-black uppercase tracking-wider transition group-hover:border-[#c9a35e] group-hover:text-[#e8c986]">Request private tour</button></div></article>)}</div></section>
 <section className="bg-[#f1e7d5] text-[#17130e]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-2"><div><div className="text-xs font-black uppercase tracking-[.25em] text-[#8d6a32]">Finance tool</div><h2 className="mt-3 font-serif text-5xl">Mortgage estimator</h2><p className="mt-4 max-w-md text-black/55">Interactive affordability tools keep high-intent buyers engaged before they speak to sales.</p></div><div className="rounded-none bg-white p-7 shadow-xl"><label className="font-bold">Loan amount: ₹{(principal/100000).toFixed(0)}L</label><input className="mt-3 w-full accent-[#8d6a32]" type="range" min="2000000" max="40000000" step="500000" value={principal} onChange={e=>setPrincipal(Number(e.target.value))}/><label className="mt-6 block font-bold">Term: {years} years</label><input className="mt-3 w-full accent-[#8d6a32]" type="range" min="5" max="30" value={years} onChange={e=>setYears(Number(e.target.value))}/><div className="mt-7 rounded-none bg-[#17130e] p-5 text-white"><div className="text-sm text-white/50">Estimated monthly EMI</div><div className="mt-1 text-4xl font-black text-[#e8c986]">₹{emi.toLocaleString("en-IN")}</div></div></div></div></section>
 </main>
}
