import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import "../familyvisa.css";
import "../family-landing.css";
import "../service-hero.css";
import PreviewNav from "../PreviewNav";

const entries: Record<string, { title: string; eyebrow: string; description: string; documents: string[]; steps: string[] }> = {
  "family-residence-visa": { title: "Family Residence Visa", eyebrow: "UAE RESIDENCY", description: "Guidance for sponsoring a spouse, child or parent in the UAE, from document preparation through residence completion.", documents: ["Sponsor passport and Emirates ID", "Dependent passport and recent photo", "Attested marriage or birth certificate", "Salary and accommodation evidence"], steps: ["Check eligibility", "Prepare documents", "Submit application", "Medical and Emirates ID", "Residence completion"] },
  "golden-visa": { title: "Golden Visa", eyebrow: "LONG-TERM RESIDENCY", description: "Explore property, professional, investor and specialist pathways for long-term UAE residency.", documents: ["Passport and current UAE status", "Route-specific eligibility evidence", "Property, company or professional documents", "Supporting financial information"], steps: ["Choose your pathway", "Confirm eligibility", "Prepare evidence", "Submit and track", "Complete residence formalities"] },
  "property-investor-visa": { title: "Property Investor Visa", eyebrow: "PROPERTY RESIDENCY", description: "Understand the documents and route considerations for UAE residency connected to qualifying property ownership.", documents: ["Passport and Emirates ID", "Title deed or property evidence", "Supporting financial documents", "Current visa and status information"], steps: ["Review property route", "Check documents", "Confirm eligibility", "File application", "Complete residency steps"] },
  "newborn-visa": { title: "Newborn Visa", eyebrow: "NEWBORN RESIDENCY", description: "A clear checklist for parents applying for a UAE residence visa for a baby born in the UAE.", documents: ["Baby passport and photo", "UAE birth certificate", "Sponsor passport and Emirates ID", "Attested relationship documents where required"], steps: ["Check timeline", "Prepare documents", "Apply for entry/residence", "Complete ID formalities", "Receive confirmation"] },
  "emirates-id": { title: "Emirates ID Services", eyebrow: "IDENTITY SERVICES", description: "Support for new Emirates ID applications, renewals, replacement and related medical-fitness requirements.", documents: ["Passport and current residence status", "Existing Emirates ID if applicable", "Recent photograph", "Route-specific supporting papers"], steps: ["Choose service", "Confirm requirements", "Book or prepare", "Submit application", "Track delivery"] },
  "document-attestation": { title: "Document Attestation", eyebrow: "DOCUMENT SERVICES", description: "Understand the document checks and attestation route required for use in the UAE.", documents: ["Original document", "Passport copy", "Issuing-country details", "Any required translations"], steps: ["Review document", "Confirm attestation route", "Prepare translation if needed", "Submit for processing", "Receive completed document"] },
  "domestic-worker-visa": { title: "Domestic Worker Visa", eyebrow: "HOUSEHOLD SERVICES", description: "Guidance for household employers preparing a domestic worker visa route and related documentation.", documents: ["Sponsor passport and Emirates ID", "Employment and household information", "Accommodation and salary evidence", "Worker passport and photo"], steps: ["Review eligibility", "Prepare employer and worker documents", "File application", "Complete medical and ID steps", "Track completion"] },
  "pro-services": { title: "PRO Services", eyebrow: "BUSINESS & PRO", description: "Practical support for government-facing business paperwork, submissions and follow-up in the UAE.", documents: ["Company trade licence", "Owner or authorised signatory ID", "Service-specific government documents", "Current immigration or labour records"], steps: ["Define the service", "Review documents", "Confirm authority requirements", "Submit and follow up", "Receive status update"] },
  "government-processing": { title: "Government Processing", eyebrow: "BUSINESS & PRO", description: "A clear starting point for government application processing and related UAE business documentation.", documents: ["Entity documents", "Authorised signatory documents", "Application-specific forms", "Supporting approvals where required"], steps: ["Review request", "Check authority requirements", "Prepare application", "Submit through the right channel", "Track result"] },
  "immigration-services": { title: "Immigration Services", eyebrow: "BUSINESS & PRO", description: "Guidance for immigration-related applications, status questions and supporting documentation.", documents: ["Passport copies", "Current visa or entry status", "Emirates ID where applicable", "Route-specific evidence"], steps: ["Understand the requirement", "Check status", "Prepare documents", "Submit application", "Receive next-step guidance"] },
  "business-support": { title: "Business Support", eyebrow: "BUSINESS & PRO", description: "Support for organisations that need help navigating routine UAE documentation and authority processes.", documents: ["Trade licence", "Company ownership documents", "Authorisation information", "Request-specific records"], steps: ["Discuss your request", "Prepare records", "Confirm process", "Submit and coordinate", "Close the request"] },
  "legal-translation": { title: "Legal Translation", eyebrow: "DOCUMENT SERVICES", description: "Prepare documents for UAE use with clear guidance on translation and supporting attestation requirements.", documents: ["Clear source document", "Language requirement", "Passport copy where needed", "Existing attestation records"], steps: ["Review document", "Confirm translation requirement", "Prepare certified translation", "Check related attestation", "Receive final copy"] },
  "power-of-attorney": { title: "Power of Attorney", eyebrow: "DOCUMENT SERVICES", description: "Understand the information and documents commonly needed before preparing a UAE power of attorney.", documents: ["Principal passport and Emirates ID", "Attorney details", "Purpose and scope of authority", "Supporting legal documents"], steps: ["Discuss your requirement", "Prepare draft information", "Review legal wording", "Complete required formalities", "Receive final document"] },
  "wills-testament": { title: "Wills & Testament", eyebrow: "DOCUMENT SERVICES", description: "A clear starting point for preparing a will or testament with the right supporting information.", documents: ["Identity documents", "Asset and family information", "Executor details", "Relevant supporting records"], steps: ["Initial discussion", "Prepare information", "Review draft", "Complete formalities", "Store final documents"] },
  "family-visa-renewal": { title: "Family Visa Renewal", eyebrow: "FAMILY RESIDENCY", description: "A route-specific renewal checklist for families keeping UAE residence documents current.", documents: ["Sponsor Emirates ID", "Dependent passport and current visa", "Relationship document", "Recent photograph where required"], steps: ["Check expiry and status", "Prepare renewal documents", "Complete medical if required", "Renew residence and Emirates ID", "Confirm delivery or completion"] },
  "emirates-id-renewal": { title: "Emirates ID Renewal", eyebrow: "IDENTITY SERVICES", description: "Prepare for Emirates ID renewal with the right current documents and route-specific checks.", documents: ["Current Emirates ID", "Passport copy", "Current visa or residence details", "Recent photo where required"], steps: ["Check renewal timing", "Review records", "Submit renewal", "Complete biometrics if requested", "Track card delivery"] },
  "emirates-id-replacement": { title: "Lost or Damaged Emirates ID", eyebrow: "IDENTITY SERVICES", description: "A practical starting point for replacing a lost or damaged Emirates ID.", documents: ["Passport copy", "Current residence details", "Lost or damaged card information", "Recent photo where required"], steps: ["Confirm replacement route", "Prepare identification", "Submit replacement request", "Complete biometrics if requested", "Track replacement card"] },
  "medical-fitness": { title: "Medical Fitness Guidance", eyebrow: "IDENTITY SERVICES", description: "Understand the practical documents and appointment steps around UAE medical-fitness requirements.", documents: ["Passport copy", "Entry permit or current visa", "Emirates ID if applicable", "Appointment or application reference"], steps: ["Confirm medical requirement", "Prepare appointment documents", "Attend approved centre", "Receive result", "Continue residence journey"] },
  "amer-center": { title: "Amer Center Guidance", eyebrow: "GOVERNMENT SERVICES", description: "A starting point for understanding the documents and appointment information often needed for Dubai immigration service visits.", documents: ["Passport copy", "Current visa or entry details", "Emirates ID where applicable", "Application reference"], steps: ["Understand your request", "Prepare documents", "Confirm the right service channel", "Attend or submit", "Track next step"] },
  "dld-trustee-services": { title: "DLD Trustee Services", eyebrow: "PROPERTY SERVICES", description: "Guidance for property-document and Dubai Land Department trustee-service preparation.", documents: ["Owner identification", "Property documents", "Authorisation where applicable", "Transaction-specific records"], steps: ["Review the request", "Prepare property papers", "Confirm trustee requirements", "Complete the relevant step", "Retain final records"] },
  "property-revaluation": { title: "Property Revaluation Guidance", eyebrow: "PROPERTY SERVICES", description: "A practical starting point for owners exploring property revaluation documentation and next steps.", documents: ["Title deed", "Owner identification", "Property information", "Supporting valuation records"], steps: ["Review property records", "Confirm purpose", "Prepare documentation", "Request the relevant service", "Review outcome"] },
  "iloe": { title: "ILOE Guidance", eyebrow: "EMPLOYMENT SERVICES", description: "Understand the key information to prepare when you need help navigating ILOE-related requirements.", documents: ["Emirates ID", "Employment information", "Policy or registration details", "Relevant supporting records"], steps: ["Review current situation", "Prepare account details", "Confirm next action", "Use the relevant official channel", "Keep confirmation records"] },
  "check-visa-status": { title: "Check UAE Visa Status", eyebrow: "IMMIGRATION SERVICES", description: "A clear starting point when you need to understand which details are useful for checking a current UAE visa status.", documents: ["Passport details", "Visa or entry-permit information", "Application reference if available", "Current status screenshots"], steps: ["Collect reference details", "Identify official status channel", "Check current information", "Review any required action", "Ask for guidance if unclear"] },
};

export function generateStaticParams() { return Object.keys(entries).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const entry = entries[slug]; return { title: { absolute: `${entry?.title ?? "Service"} | FamilyVisaUAE` } }; }
const calculatorFor: Record<string, { href: string; label: string }> = {
  "family-residence-visa": { href: "/demos/familyvisauae/calculators/family", label: "Calculate family visa cost" },
  "golden-visa": { href: "/demos/familyvisauae/calculators/golden", label: "Check Golden Visa route" },
  "property-investor-visa": { href: "/demos/familyvisauae/calculators/property", label: "Check property visa route" },
  "newborn-visa": { href: "/demos/familyvisauae/calculators/newborn", label: "Check newborn visa route" },
  "pro-services": { href: "/demos/familyvisauae/calculators/pro", label: "Request a PRO estimate" },
};
const themeFor = (slug: string) => /golden|property|dld|revaluation/.test(slug) ? "residency" : /document|translation|attorney|wills/.test(slug) ? "documents" : /pro|government|business|immigration/.test(slug) ? "business" : /emirates|medical|amer|iloe|status/.test(slug) ? "support" : "family";
export default async function ServicePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const entry = entries[slug] ?? entries["family-residence-visa"]; const calculator = calculatorFor[slug] ?? { href: "/demos/familyvisauae/checklist", label: "Open document checker" }; const message = encodeURIComponent(`Hi FamilyVisaUAE, I need help with ${entry.title}. Please share the eligibility and document checklist.`); const visual = /family|newborn/.test(slug) ? "/familyvisauae-family-balcony-v2.png" : /document|translation|attestation|attorney|wills/.test(slug) ? "/familyvisauae-document-review-v2.png" : "/familyvisauae-team.png"; const theme = themeFor(slug); return <main className={`fv fv-service-page fv-theme-${theme}`}><div className="fv-top"><span>FamilyVisaUAE</span><span>UAE visa & document services</span></div><PreviewNav /><section className="fv-hero fv-service-hero" style={{ minHeight: "55vh" }}><Image className="fv-service-hero-image" src={visual} alt="FamilyVisaUAE service support in Dubai" width={1792} height={1024} sizes="100vw" priority /><div><p className="eyebrow">{entry.eyebrow}</p><h1>{entry.title}, <em>made clearer.</em></h1><p className="lead">{entry.description}</p><div className="fv-cta"><Link className="primary" href={calculator.href}>{calculator.label} →</Link><a className="secondary" href={`https://wa.me/971566556645?text=${message}`} target="_blank" rel="noreferrer">Chat on WhatsApp</a></div></div></section><section className="fv-section"><div className="section-head"><div><p className="eyebrow">WHAT TO PREPARE</p><h2>Your document checklist.</h2></div></div><div className="service-grid">{entry.documents.map((item, index) => <article key={item}><span>0{index + 1}</span><h3>{item}</h3><p>Your final requirements are confirmed by our team for your individual route.</p></article>)}</div></section><section className="fv-process"><div><p className="eyebrow">SIMPLE PROCESS</p><h2>What happens next.</h2></div><ol>{entry.steps.map((step, index) => <li key={step}><b>0{index + 1}</b><span>{step}</span></li>)}</ol></section><section className="fv-approval"><p className="eyebrow">NEED A CONFIRMED ANSWER?</p><h2>Get route-specific guidance.</h2><p>We are a private consultancy. Government requirements and fees are subject to the relevant official authority.</p><a className="primary" href={`https://wa.me/971566556645?text=${message}`} target="_blank" rel="noreferrer">Ask our team on WhatsApp</a></section></main>; }
