import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import Image from "next/image";
import "../familyvisa.css";
import "../family-landing.css";
import "../service-hero.css";
import PreviewNav from "../PreviewNav";
import WhatsAppIconLink from "../WhatsAppIconLink";

const entries: Record<string, { title: string; eyebrow: string; description: string; documents: string[]; steps: string[] }> = {
  "family-visa-cost": { title: "Family Visa Cost", eyebrow: "FAMILY VISA FEES", description: "A clear breakdown of the main government-fee stages in a UAE family sponsorship file, with inside-country, outside-country and renewal planning routes.", documents: ["Sponsor salary or employment evidence", "Applicant passport copy", "Current UAE status or entry details", "Preferred residence duration"], steps: ["Confirm dependent and location", "Identify entry or status-change route", "Add medical and Emirates ID where applicable", "Separate authority and support fees", "Confirm the current itemised quote"] },
  "golden-visa-cost": { title: "Golden Visa Cost", eyebrow: "GOLDEN VISA FEES", description: "Understand the property or eligibility side, immigration stages, medical fitness and ten-year Emirates ID costs before choosing a Golden Visa package.", documents: ["Passport and current UAE status", "Golden Visa eligibility evidence", "Property or professional records", "Dependant details where applicable"], steps: ["Confirm Golden Visa pathway", "Review route-specific authority charges", "Add medical and Emirates ID", "Identify dependant additions", "Confirm current package scope"] },
  "amer-centres-near-me": { title: "Amer Centres Near Me", eyebrow: "AMER CENTRE GUIDE", description: "Find the right Dubai Amer service route or complete eligible visa and residency transactions online without waiting at a physical typing centre.", documents: ["Passport and current visa details", "Emirates ID where applicable", "Application or transaction reference", "Service-specific supporting documents"], steps: ["Identify the transaction you need", "Choose online support or an authorised centre", "Prepare the required documents", "Complete submission or appointment", "Track the result"] },
  "amer-services-home": { title: "Amer Services at Home", eyebrow: "AMER SUPPORT", description: "Remote preparation and coordination for common Dubai immigration-service steps that would otherwise require a service-centre visit.", documents: ["Passport and visa copies", "Emirates ID where applicable", "Application or transaction reference", "Service-specific supporting documents"], steps: ["Identify the required transaction", "Review documents remotely", "Prepare the application", "Coordinate submission or appointment", "Track the next step"] },
  "health-insurance": { title: "Health Insurance", eyebrow: "RESIDENCY SUPPORT", description: "Guidance on compliant health-cover requirements for residents and dependants before residence issuance or renewal.", documents: ["Passport and Emirates ID", "Current or planned visa route", "Emirate of residence", "Coverage needs and dependant details"], steps: ["Confirm visa and emirate", "Review required cover", "Compare suitable options", "Arrange policy documentation", "Continue the residence process"] },
  "emirates-id-typing": { title: "Emirates ID Typing", eyebrow: "IDENTITY SERVICES", description: "Accurate preparation of Emirates ID application details so passport, visa and identity records match before submission.", documents: ["Passport bio page", "Current visa or entry permit", "Application reference", "Contact and delivery details"], steps: ["Review identity records", "Check names and passport data", "Prepare application details", "Submit through the relevant channel", "Track biometrics or delivery"] },
  "emirates-id-typing-service": { title: "Emirates ID Typing", eyebrow: "IDENTITY SERVICES", description: "Accurate preparation of Emirates ID application details so passport, visa and identity records match before submission.", documents: ["Passport bio page", "Current visa or entry permit", "Application reference", "Contact and delivery details"], steps: ["Review identity records", "Check names and passport data", "Prepare application details", "Submit through the relevant channel", "Track biometrics or delivery"] },
  "family-residence-visa": { title: "Family Residence Visa", eyebrow: "UAE RESIDENCY", description: "Guidance for sponsoring a spouse, child or parent in the UAE, from document preparation through residence completion.", documents: ["Sponsor passport and Emirates ID", "Dependent passport and recent photo", "Attested marriage or birth certificate", "Salary and accommodation evidence"], steps: ["Check eligibility", "Prepare documents", "Submit application", "Medical and Emirates ID", "Residence completion"] },
  "golden-visa": { title: "Golden Visa", eyebrow: "LONG-TERM RESIDENCY", description: "Explore property, professional, investor and specialist pathways for long-term UAE residency.", documents: ["Passport and current UAE status", "Route-specific eligibility evidence", "Property, company or professional documents", "Supporting financial information"], steps: ["Choose your pathway", "Confirm eligibility", "Prepare evidence", "Submit and track", "Complete residence formalities"] },
  "property-investor-visa": { title: "Property Investor Visa", eyebrow: "PROPERTY RESIDENCY", description: "Understand the documents and route considerations for UAE residency connected to qualifying property ownership.", documents: ["Passport and Emirates ID", "Title deed or property evidence", "Supporting financial documents", "Current visa and status information"], steps: ["Review property route", "Check documents", "Confirm eligibility", "File application", "Complete residency steps"] },
  "newborn-visa": { title: "Newborn Visa", eyebrow: "NEWBORN RESIDENCY", description: "A clear checklist for parents applying for a UAE residence visa for a baby born in the UAE.", documents: ["Baby passport and photo", "UAE birth certificate", "Sponsor passport and Emirates ID", "Attested relationship documents where required"], steps: ["Check timeline", "Prepare documents", "Apply for entry/residence", "Complete ID formalities", "Receive confirmation"] },
  "emirates-id": { title: "Emirates ID Services", eyebrow: "IDENTITY SERVICES", description: "Support for new Emirates ID applications, renewals, replacement and related medical-fitness requirements.", documents: ["Passport and current residence status", "Existing Emirates ID if applicable", "Recent photograph", "Route-specific supporting papers"], steps: ["Choose service", "Confirm requirements", "Book or prepare", "Submit application", "Track delivery"] },
  "document-attestation": { title: "Document Attestation", eyebrow: "DOCUMENT SERVICES", description: "Understand the document checks and attestation route required for use in the UAE.", documents: ["Original document", "Passport copy", "Issuing-country details", "Any required translations"], steps: ["Review document", "Confirm attestation route", "Prepare translation if needed", "Submit for processing", "Receive completed document"] },
  "domestic-worker-visa": { title: "Domestic Worker Visa", eyebrow: "HOUSEHOLD SERVICES", description: "Guidance for household employers preparing a domestic worker visa route and related documentation.", documents: ["Sponsor passport and Emirates ID", "Employment and household information", "Accommodation and salary evidence", "Worker passport and photo"], steps: ["Review eligibility", "Prepare employer and worker documents", "File application", "Complete medical and ID steps", "Track completion"] },
  "pro-services": { title: "PRO Services", eyebrow: "BUSINESS & PRO", description: "Practical support for government-facing business paperwork, submissions and follow-up in the UAE.", documents: ["Company trade licence", "Owner or authorised signatory ID", "Service-specific government documents", "Current immigration or labour records"], steps: ["Define the service", "Review documents", "Confirm authority requirements", "Submit and follow up", "Receive status update"] },
  "government-processing": { title: "Government Processing", eyebrow: "BUSINESS & PRO", description: "A clear starting point for government application processing and related UAE business documentation.", documents: ["Entity documents", "Authorised signatory documents", "Application-specific forms", "Supporting approvals where required"], steps: ["Review request", "Check authority requirements", "Prepare application", "Submit through the right channel", "Track result"] },
  "immigration-services": { title: "Immigration Services", eyebrow: "BUSINESS & PRO", description: "Guidance for immigration-related applications, status questions and supporting documentation.", documents: ["Passport copies", "Current visa or entry status", "Emirates ID where applicable", "Route-specific evidence"], steps: ["Understand the requirement", "Check status", "Prepare documents", "Submit application", "Receive next-step guidance"] },
  "business-support": { title: "Business Support", eyebrow: "BUSINESS & PRO", description: "Support for organisations that need help navigating routine UAE documentation and authority processes.", documents: ["Trade licence", "Company ownership documents", "Authorisation information", "Request-specific records"], steps: ["Discuss your request", "Prepare records", "Confirm process", "Submit and coordinate", "Close the request"] },
  "legal-translation": { title: "Legal Translation", eyebrow: "DOCUMENT SERVICES", description: "Prepare documents for UAE use with clear guidance on translation and supporting attestation requirements.", documents: ["Clear source document", "Language requirement", "Passport copy where needed", "Existing attestation records"], steps: ["Review document", "Confirm translation requirement", "Prepare certified translation", "Check related attestation", "Receive final copy"] },
  "power-of-attorney": { title: "Power of Attorney", eyebrow: "DOCUMENT SERVICES", description: "Understand the information and documents commonly needed before preparing a UAE power of attorney.", documents: ["Principal passport and Emirates ID", "Attorney details", "Purpose and scope of authority", "Supporting legal documents"], steps: ["Discuss your requirement", "Prepare draft information", "Review legal wording", "Complete required formalities", "Receive final document"] },
  "wills-testament": { title: "Wills & Testament", eyebrow: "DOCUMENT SERVICES", description: "A clear starting point for preparing a will or testament with the right supporting information.", documents: ["Identity documents", "Asset and family information", "Executor details", "Relevant supporting records"], steps: ["Initial discussion", "Prepare information", "Review draft", "Complete formalities", "Store final documents"] },
  "family-visa-renewal": { title: "Family Visa Renewal", eyebrow: "FAMILY RESIDENCY", description: "A route-specific renewal checklist for families keeping UAE residence documents current.", documents: ["Sponsor Emirates ID", "Dependent passport and current visa", "Relationship document", "Recent photograph where required"], steps: ["Check expiry and status", "Prepare renewal documents", "Complete medical if required", "Renew residence and Emirates ID", "Confirm delivery or completion"] },
  "employment-visa": { title: "Employment Visa", eyebrow: "EMPLOYMENT RESIDENCY", description: "Guidance for UAE employment residence processing, from the initial work-permit stage through medical fitness, Emirates ID and residence formalities.", documents: ["Passport copy and recent photograph", "Signed employment or offer documents", "Employer or establishment information", "Education or professional evidence where the role requires it"], steps: ["Confirm employment route", "Prepare employer and employee documents", "Complete permit and status formalities", "Medical fitness and Emirates ID", "Complete residence process"] },
  "business-setup": { title: "Business Setup", eyebrow: "BUSINESS SERVICES", description: "A clear starting point for entrepreneurs comparing UAE company setup routes and the government documentation that follows.", documents: ["Shareholder passport and identity details", "Proposed business activities and trade name", "Ownership and company structure information", "Route-specific approvals or supporting evidence"], steps: ["Define activity and ownership", "Compare the appropriate setup route", "Prepare approvals and company documents", "Complete licensing formalities", "Continue with establishment and immigration services"] },
  "spouse-visa": { title: "Spouse Residence Visa", eyebrow: "FAMILY RESIDENCY", description: "Practical guidance for UAE residents sponsoring a husband or wife, including relationship evidence and residence formalities.", documents: ["Sponsor passport, residence and Emirates ID", "Spouse passport and recent photograph", "Attested marriage certificate", "Income and accommodation evidence where required"], steps: ["Confirm sponsor eligibility", "Prepare attested relationship documents", "Submit the residence application", "Complete medical and Emirates ID requirements", "Complete residence formalities"] },
  "children-visa": { title: "Children Residence Visa", eyebrow: "FAMILY RESIDENCY", description: "A clear route for parents preparing UAE residence applications for eligible dependent children.", documents: ["Sponsor passport, residence and Emirates ID", "Child passport and photograph", "Attested birth certificate", "Income and accommodation evidence where required"], steps: ["Check dependent eligibility", "Prepare relationship evidence", "Submit application", "Complete age-appropriate formalities", "Complete residence process"] },
  "parents-visa": { title: "Parents Residence Visa", eyebrow: "FAMILY RESIDENCY", description: "Guidance for UAE residents exploring sponsorship of eligible parents and the supporting evidence commonly required.", documents: ["Sponsor passport, residence and Emirates ID", "Parent passport and photograph", "Relationship evidence", "Income, accommodation and other route-specific evidence"], steps: ["Check sponsorship conditions", "Prepare relationship and support evidence", "Submit application", "Complete medical and Emirates ID requirements", "Complete residence formalities"] },
  "emirates-id-renewal": { title: "Emirates ID Renewal", eyebrow: "IDENTITY SERVICES", description: "Prepare for Emirates ID renewal with the right current documents and route-specific checks.", documents: ["Current Emirates ID", "Passport copy", "Current visa or residence details", "Recent photo where required"], steps: ["Check renewal timing", "Review records", "Submit renewal", "Complete biometrics if requested", "Track card delivery"] },
  "emirates-id-replacement": { title: "Lost or Damaged Emirates ID", eyebrow: "IDENTITY SERVICES", description: "A practical starting point for replacing a lost or damaged Emirates ID.", documents: ["Passport copy", "Current residence details", "Lost or damaged card information", "Recent photo where required"], steps: ["Confirm replacement route", "Prepare identification", "Submit replacement request", "Complete biometrics if requested", "Track replacement card"] },
  "medical-fitness": { title: "Medical Fitness Guidance", eyebrow: "IDENTITY SERVICES", description: "Understand the practical documents and appointment steps around UAE medical-fitness requirements.", documents: ["Passport copy", "Entry permit or current visa", "Emirates ID if applicable", "Appointment or application reference"], steps: ["Confirm medical requirement", "Prepare appointment documents", "Attend approved centre", "Receive result", "Continue residence journey"] },
  "amer-center": { title: "Amer Center Guidance", eyebrow: "GOVERNMENT SERVICES", description: "A starting point for understanding the documents and appointment information often needed for Dubai immigration service visits.", documents: ["Passport copy", "Current visa or entry details", "Emirates ID where applicable", "Application reference"], steps: ["Understand your request", "Prepare documents", "Confirm the right service channel", "Attend or submit", "Track next step"] },
  "dld-trustee-services": { title: "DLD Trustee Services", eyebrow: "PROPERTY SERVICES", description: "Guidance for property-document and Dubai Land Department trustee-service preparation.", documents: ["Owner identification", "Property documents", "Authorisation where applicable", "Transaction-specific records"], steps: ["Review the request", "Prepare property papers", "Confirm trustee requirements", "Complete the relevant step", "Retain final records"] },
  "property-revaluation": { title: "Property Revaluation Guidance", eyebrow: "PROPERTY SERVICES", description: "A practical starting point for owners exploring property revaluation documentation and next steps.", documents: ["Title deed", "Owner identification", "Property information", "Supporting valuation records"], steps: ["Review property records", "Confirm purpose", "Prepare documentation", "Request the relevant service", "Review outcome"] },
  "iloe": { title: "ILOE Guidance", eyebrow: "EMPLOYMENT SERVICES", description: "Understand the key information to prepare when you need help navigating ILOE-related requirements.", documents: ["Emirates ID", "Employment information", "Policy or registration details", "Relevant supporting records"], steps: ["Review current situation", "Prepare account details", "Confirm next action", "Use the relevant official channel", "Keep confirmation records"] },
  "check-visa-status": { title: "Check UAE Visa Status", eyebrow: "IMMIGRATION SERVICES", description: "A clear starting point when you need to understand which details are useful for checking a current UAE visa status.", documents: ["Passport details", "Visa or entry-permit information", "Application reference if available", "Current status screenshots"], steps: ["Collect reference details", "Identify official status channel", "Check current information", "Review any required action", "Ask for guidance if unclear"] },
  "new-employee-visa": { title: "New Employee Visa", eyebrow: "EMPLOYMENT & PRO", description: "End-to-end preparation guidance for a new UAE employee residence route, including the connected labour, immigration, medical and identity stages.", documents: ["Employee passport and photograph", "Offer or employment documents", "Employer establishment information", "Qualification evidence where required"], steps: ["Confirm job and permit route", "Prepare employer and employee file", "Complete work-permit and immigration stages", "Medical fitness and Emirates ID", "Complete residence and labour formalities"] },
  "employee-visa-renewal": { title: "Employee Visa Renewal", eyebrow: "EMPLOYMENT & PRO", description: "A practical renewal route for employers keeping employee work and residence records current.", documents: ["Employee passport and current residence", "Emirates ID", "Current labour or employment records", "Employer establishment documents"], steps: ["Check expiry dates", "Review employment records", "Submit renewal stages", "Complete medical and Emirates ID renewal", "Confirm updated records"] },
  "relative-work-permit": { title: "Relative Work Permit", eyebrow: "WORK PERMITS", description: "Guidance for employers hiring an eligible person who already holds family or dependent residence in the UAE.", documents: ["Employee passport and Emirates ID", "Current dependent residence", "Employer establishment records", "Employment offer and permit information"], steps: ["Confirm existing residence", "Check work-permit route", "Prepare employer submission", "Complete required labour formalities", "Confirm permit status"] },
  "golden-visa-work-permit": { title: "Golden Visa Work Permit", eyebrow: "WORK PERMITS", description: "Support for employers preparing the appropriate work-permit route for an eligible Golden Visa holder.", documents: ["Golden Visa holder passport and Emirates ID", "Current long-term residence evidence", "Employer establishment records", "Employment offer information"], steps: ["Confirm residence status", "Identify work-permit route", "Prepare employer file", "Submit labour application", "Confirm permit completion"] },
  "part-time-work-permit": { title: "Part-Time & Intern Work Permit", eyebrow: "WORK PERMITS", description: "A clear starting point for employers considering compliant part-time or internship permit routes.", documents: ["Worker passport and identity records", "Current residence status", "Employer establishment information", "Role and working-arrangement details"], steps: ["Confirm permit type", "Check worker status", "Prepare employment records", "Submit through the relevant channel", "Confirm permit result"] },
  "visa-cancellation": { title: "Visa Cancellation", eyebrow: "IMMIGRATION & PRO", description: "Guidance for preparing labour and residence cancellation steps when an employee or resident is leaving or changing status.", documents: ["Passport and Emirates ID", "Current visa or residence details", "Employment or sponsor information", "Application references where available"], steps: ["Confirm cancellation scope", "Review labour obligations if applicable", "Prepare immigration cancellation", "Submit through relevant channels", "Keep cancellation confirmation"] },
  "emirates-id-cost": { title: "Emirates ID Fees & Cost Guide", eyebrow: "IDENTITY SERVICES", description: "Understand the common fee components that can apply to Emirates ID issuance, renewal and replacement before requesting a confirmed quote.", documents: ["Visa duration or residence route", "Current Emirates ID if applicable", "Passport and identity details", "Urgency or replacement information"], steps: ["Choose the ID service", "Confirm visa duration", "Review applicable authority charges", "Check optional or urgent services", "Request the current confirmed amount"] },
  "visa-medical": { title: "Visa Medical Fitness", eyebrow: "MEDICAL FITNESS", description: "Prepare for the UAE medical-fitness stage connected to eligible residence applications and renewals.", documents: ["Passport copy", "Entry permit or current residence", "Application reference where available", "Emirates ID if already issued"], steps: ["Confirm whether medical is required", "Choose the appropriate approved centre", "Prepare appointment documents", "Complete the examination", "Continue the residence process after the result"] },
  "document-photo-specifications": { title: "Visa Document & Photo Specifications", eyebrow: "DOCUMENT READINESS", description: "Prepare clear passport, identity and visa-photo files before submission so avoidable image-quality problems do not hold up your application.", documents: ["Clear colour passport copy with all edges visible", "Recent passport-style photograph on a plain background", "Readable Emirates ID copies where applicable", "Clear relationship or supporting certificates"], steps: ["Check document validity", "Capture complete uncropped copies", "Review clarity and glare", "Confirm photo format for the selected route", "Keep originals available if requested"] },
  "medical-id-centres": { title: "Medical Fitness & Emirates ID Centre Guidance", eyebrow: "APPOINTMENT GUIDANCE", description: "Understand when an in-person medical fitness or biometrics visit may be required and what to prepare before choosing an authorised centre.", documents: ["Passport and application details", "Entry permit or current residence", "Emirates ID application reference where available", "Appointment or transaction reference"], steps: ["Confirm which in-person step applies", "Use the relevant official channel to identify an authorised centre", "Prepare the required documents", "Attend the appointment", "Continue the residence or ID process"] },
};

export const serviceSlugs = Object.keys(entries);
export const dynamicParams = false;
export function generateStaticParams() { return serviceSlugs.map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const entry = entries[slug]; if (!entry) notFound(); const title = `${entry.title} | FamilyVisaUAE`; const description = entry.description; return { title: { absolute: title }, description, alternates: { canonical: `/demos/familyvisauae/${slug}` }, openGraph: { title, description }, twitter: { title, description } }; }
const calculatorFor: Record<string, { href: string; label: string }> = {
  "family-residence-visa": { href: "/demos/familyvisauae/calculators/family", label: "Calculate family visa cost" },
  "golden-visa": { href: "/demos/familyvisauae/calculators/golden", label: "Check Golden Visa route" },
  "property-investor-visa": { href: "/demos/familyvisauae/calculators/property", label: "Check property visa route" },
  "newborn-visa": { href: "/demos/familyvisauae/calculators/newborn", label: "Check newborn visa route" },
  "pro-services": { href: "/demos/familyvisauae/calculators/pro", label: "Request a PRO estimate" },
};
const themeFor = (slug: string) => /golden|property|dld|revaluation/.test(slug) ? "residency" : /document|translation|attorney|wills/.test(slug) ? "documents" : /pro|government|business|immigration|employee|employment|work-permit|cancellation/.test(slug) ? "business" : /emirates|medical|amer|iloe|status/.test(slug) ? "support" : "family";
export default async function ServicePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const entry = entries[slug]; if (!entry) notFound(); const calculator = calculatorFor[slug] ?? { href: "/demos/familyvisauae/checklist", label: "Open document checker" }; const message = encodeURIComponent(`Hi FamilyVisaUAE, I need help with ${entry.title}. Please share the eligibility and document checklist.`); const visual = /family|newborn|spouse|children|parents/.test(slug) ? "/familyvisauae-family-balcony-v2.png" : /document|translation|attestation|attorney|wills/.test(slug) ? "/familyvisauae-document-review-v2.png" : /business|pro|employee|employment|work-permit|government|immigration|cancellation/.test(slug) ? "/familyvisauae-consultation-v1.png" : "/familyvisauae-team.png"; const theme = themeFor(slug); return <main className={`fv fv-service-page fv-theme-${theme}`}><div className="fv-top"><span>FamilyVisaUAE</span><span>UAE visa & document services</span></div><PreviewNav /><section className="fv-hero fv-service-hero" style={{ minHeight: "55vh" }}><Image className="fv-service-hero-image" src={visual} alt="FamilyVisaUAE service support in Dubai" width={1792} height={1024} sizes="100vw" priority /><div><p className="eyebrow">{entry.eyebrow}</p><h1>{entry.title}, <em>made clearer.</em></h1><p className="lead">{entry.description}</p><div className="fv-cta"><Link className="primary" href={calculator.href}>{calculator.label} →</Link><WhatsAppIconLink href={`https://wa.me/9718003627?text=${message}`} label={`Ask about ${entry.title} on WhatsApp`}/></div></div></section><section className="fv-section"><div className="section-head"><div><p className="eyebrow">WHAT TO PREPARE</p><h2>Your document checklist.</h2></div></div><div className="service-grid">{entry.documents.map((item, index) => <article key={item}><span>0{index + 1}</span><h3>{item}</h3><p>Your final requirements are confirmed by our team for your individual route.</p></article>)}</div></section><section className="fv-process"><div><p className="eyebrow">SIMPLE PROCESS</p><h2>What happens next.</h2></div><ol>{entry.steps.map((step, index) => <li key={step}><b>0{index + 1}</b><span>{step}</span></li>)}</ol></section><section className="fv-approval"><p className="eyebrow">NEED A CONFIRMED ANSWER?</p><h2>Get route-specific guidance.</h2><p>We are a private consultancy. Government requirements and fees are subject to the relevant official authority.</p><div className="fv-cta"><span>Continue privately on WhatsApp</span><WhatsAppIconLink href={`https://wa.me/9718003627?text=${message}`} label={`Ask FamilyVisaUAE about ${entry.title}`}/></div></section></main>; }



