"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {products} from "../catalog";
type Line={id:number;qty:number}; const KEY="barraid-cart";
export default function Cart(){
 const [cart,setCart]=useState<Line[]>([]);
 useEffect(()=>{try{const a=JSON.parse(localStorage.getItem(KEY)||"[]");setCart(Array.isArray(a)?a:[])}catch{}},[]);
 const save=(a:Line[])=>{setCart(a);localStorage.setItem(KEY,JSON.stringify(a))};
 const rows=cart.map(x=>({line:x,p:products.find(p=>p.id===x.id)})).filter(x=>x.p);
 const subtotal=rows.reduce((n,x)=>n+x.p!.price*x.line.qty,0);
 const retail=rows.reduce((n,x)=>n+(x.p!.oldPrice||x.p!.price)*x.line.qty,0), savings=Math.max(0,retail-subtotal);
 const count=rows.reduce((n,x)=>n+x.line.qty,0);
 const qty=(id:number,n:number)=>save(n<1?cart.filter(x=>x.id!==id):cart.map(x=>x.id===id?{...x,qty:Math.min(20,n)}:x));
 return <main className="min-h-screen bg-[#f5f1e8] text-[#111]">
  <header className="sticky top-0 z-30 border-b border-black/10 bg-[#fffdf8]/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><Link href="/demos/barraid" className="text-2xl font-black tracking-[-.07em]">BAR<span className="text-[#b51f28]">RAID</span></Link><Link href="/demos/barraid/shop" className="rounded-full border border-black/15 bg-white px-4 py-2 text-sm font-black">← Continue shopping</Link></div></header>
  <section className="mx-auto max-w-6xl px-5 py-10 sm:py-14">
   <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[.2em] text-[#b51f28]">Your selection</div><h1 className="mt-2 text-4xl font-black tracking-[-.05em] sm:text-6xl">Your cart</h1><p className="mt-2 text-sm text-black/50">{count} item{count===1?"":"s"} ready for checkout</p></div><div className="hidden text-right sm:block"><div className="text-xs font-black uppercase tracking-[.16em] text-black/35">BarRaid checkout</div><div className="mt-1 text-sm font-bold">Cart <span className="text-black/25">→</span> Details <span className="text-black/25">→</span> Confirmation</div></div></div>
   {rows.length?<div className="mt-8 grid gap-7 lg:grid-cols-[minmax(0,1fr)_23rem]">
    <div className="grid gap-4">{rows.map(({line,p})=><article key={line.id} className="overflow-hidden rounded-[1.75rem] border border-black/10 bg-white shadow-[0_12px_35px_rgba(0,0,0,.05)]"><div className="grid gap-5 p-4 sm:grid-cols-[10rem_1fr_auto] sm:p-5"><Link href={"/demos/barraid/product/"+p!.slug} className="grid min-h-40 place-items-center rounded-2xl bg-[#f8f5ee] p-3"><img src={p!.image} alt={p!.name} className="h-36 w-full object-contain"/></Link><div className="flex flex-col justify-center"><div className="text-[10px] font-black uppercase tracking-[.18em] text-[#b51f28]">{p!.category}</div><Link href={"/demos/barraid/product/"+p!.slug} className="mt-2 text-xl font-black leading-tight hover:underline">{p!.name}</Link>{p!.code&&<div className="mt-2 text-xs font-bold text-black/40">Product code · {p!.code}</div>}<div className="mt-4 flex flex-wrap items-baseline gap-2"><b className="text-xl">₹{p!.price.toLocaleString("en-IN")}</b>{p!.oldPrice&&<span className="text-sm text-black/30 line-through">₹{p!.oldPrice!.toLocaleString("en-IN")}</span>}</div></div><div className="flex items-center justify-between gap-3 sm:flex-col sm:items-end sm:justify-between"><button onClick={()=>save(cart.filter(x=>x.id!==line.id))} className="text-xs font-black text-[#b51f28] underline-offset-4 hover:underline">Remove</button><div className="flex items-center rounded-full border border-black/15 bg-[#faf8f3] p-1"><button aria-label={"Decrease "+p!.name+" quantity"} onClick={()=>qty(line.id,line.qty-1)} className="grid h-9 w-9 place-items-center rounded-full text-lg hover:bg-white">−</button><b className="min-w-9 text-center">{line.qty}</b><button disabled={line.qty>=20} aria-label={"Increase "+p!.name+" quantity"} onClick={()=>qty(line.id,line.qty+1)} className="grid h-9 w-9 place-items-center rounded-full text-lg hover:bg-white disabled:opacity-30">+</button></div><b className="hidden text-right text-lg sm:block">₹{(p!.price*line.qty).toLocaleString("en-IN")}</b></div></div></article>)}</div>
    <aside className="h-fit overflow-hidden rounded-[1.75rem] border border-black/10 bg-[#fffdf8] shadow-[0_18px_50px_rgba(0,0,0,.08)] lg:sticky lg:top-24"><div className="border-b border-black/10 p-6"><div className="text-xs font-black uppercase tracking-[.18em] text-[#b51f28]">Order summary</div><h2 className="mt-2 text-2xl font-black">Almost yours.</h2></div><div className="space-y-3 p-6 text-sm"><div className="flex justify-between"><span className="text-black/55">Subtotal</span><b>₹{subtotal.toLocaleString("en-IN")}</b></div>{savings>0&&<div className="flex justify-between text-[#355b2c]"><span>You save</span><b>−₹{savings.toLocaleString("en-IN")}</b></div>}<div className="flex justify-between gap-4"><span className="text-black/55">Shipping</span><b className="text-right">Confirmed before final order</b></div><div className="border-t border-black/10 pt-4"><div className="flex items-end justify-between"><span className="font-black">Total</span><b className="text-3xl tracking-[-.04em]">₹{subtotal.toLocaleString("en-IN")}</b></div><p className="mt-4 rounded-xl bg-[#f5f1e8] p-4 text-xs leading-5 text-black/55">Shipping charge, delivery estimate and available payment method are confirmed by BarRaid before the order is finalized.</p><Link href="/demos/barraid/checkout" className="mt-5 flex min-h-14 items-center justify-center rounded-xl bg-[#b51f28] px-5 text-center font-black text-white shadow-lg transition hover:bg-[#991a22]">Continue to checkout →</Link><div className="mt-4 flex items-center justify-center gap-2 text-[10px] font-bold uppercase tracking-wider text-black/35"><span>Secure details</span><span>·</span><span>Order support</span></div></div></div></aside>
   </div>:<div className="mt-10 rounded-[2rem] border border-black/10 bg-white p-10 text-center shadow-sm sm:p-16"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#f5f1e8] text-2xl">◌</div><h2 className="mt-5 text-3xl font-black">Your cart is empty</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-black/50">Explore BarRaid beer towers, dispensers and statement barware, then add your favourites here.</p><Link href="/demos/barraid/shop" className="mt-6 inline-block rounded-full bg-[#b51f28] px-7 py-3 font-black text-white">Explore the collection →</Link></div>}
  </section>
 </main>
}